; Modifie l'apparence de la ferme de blé.
; Version 2.
; 18/03/2006 : Créé par Syl pour la version 2.5.
; 24/06/2007 : Adapté par Syl pour la version 3.0 Béta 16.

[Batiment_1]
	;Ferme de blé
	CheminImage = Mods\SylPack\
	Image = Batiment_FermeDeBle
	Largeur = 64
	Hauteur = 64
	EntreePositionX = -10
	EntreePositionY = 0
	NombreEtapeFabrication = 9