; Ajoute un trésor aux elfes qui leur permet d'augmenter leur puissance à l'arc.
; Version 3.
; 23/01/2006 : Créé par Syl pour la version 2.5.
; 19/06/2006 : Ajout d'une durée de recharge pour la version 3.0.
; 24/06/2007 : Adapté par Syl pour la version 3.0 Béta 16.

[Objet_+]
	NomFR = Transe de la flèche
	NomEN = Arrow trance
	NomEffetFR = Archerie accrue
	NomEffetEN = Bow skill up
	CheminImage = Mods\SylPack\
	Image = Objet_TranseDeLaFleche
	NomPlurielFR = Transes de la flèche
	NomPlurielEN = Arrow trances
	DescriptionFR = Accroit votre précision à l'arc temporairement.
	DescriptionEN = Increase your bow skill temporary.
	TresorRace = 3
	Secret = 1
	Unique = 1
	Indestructible = 1
	Inseparable = 1
	Categorie = 1
	Competence = 13
	DureeFabrication = 1200
	PrixVente = 1200
	Utilisable = 1
	Experience = 3,5
	EffetAttaque = 33
	PerteMagie = 14
	BonusCompetencesObjets(13) = 5
	CreerObjet = +0
	Duree = 30
	PrixTalents = 24
	DureeRecharge = 14