; Ajoute une mitrailleuse dans l'arsenal.
; Version 1.
; 23/01/2006 : Créé par Syl pour la version 2.5.

[Objet_+]
	NomFR = Pistolet mitrailleur
	NomEN = Machine gun
	NomPlurielFR = Pistolets mitrailleurs
	NomPlurielEN = Machine guns
	CheminImage = Mods\SylPack\
	Image = Objet_PistoletMitrailleur
	DescriptionFR = Arme à feu à cadence de tir très rapide.
	DescriptionEN = Very fast shooting firearm.
	Epoque = 5
	Categorie = 1
	Competence = 15
	PrixRessources(17) = 15
	DureeFabrication = 2340
	#Indique le bâtiment dans lequel l'objet est fabriqué.
	FabricationBatiment = 37
	PrixVente = 1575
	BonusAttaque = 16
	BonusPorteeAttaque = 80
	AttaqueAutomatique = 1
	EffetAttaque = 30
	LanceProjectile = 88
	BonusCompetencesSpeciales(2) = 16
	PerteRessourceIndice = 26
	PerteRessourceQuantite = 0.1