; Ajoute un trésor commun qui permet de créer pleins de golems de pierre.
; Version 3.
; 19/03/2006 : Créé par Syl pour la version 2.5.
; 19/06/2006 : Ajout d'une durée de recharge pour la version 3.0.
; 24/06/2007 : Adapté par Syl pour la version 3.0 Béta 16.

[Objet_+]
	NomFR = Générateur de golems
	NomEN = Golems generator
	CheminImage = Mods\SylPack\
	Image = Objet_GenerateurDeGolems
	NomPlurielFR = Générateurs de golems
	NomPlurielEN = Golems generators
	DescriptionFR = Crée plein de golems de pierre avec de la pierre.
	DescriptionEN = Make lot of stone golems with stone.
	TresorRace = 0
	Secret = 1
	Unique = 1
	Indestructible = 1
	Inseparable = 1
	Categorie = 1
	Competence = 24
	DureeFabrication = 3250
	PrixVente = 3250
	Utilisable = 1
	Experience = 7
	Invocation = 31
	Quantite = 0.2
	EffetAttaque = 18
	PerteMagie = 28
	PerteRessourceIndice = 13
	PerteRessourceQuantite = 20
	PrixTalents = 65
	DureeRecharge = 60