; Ajoute un manteau de fourrure fabricable à partir de la fourrure d'un animal.
; Version 3.
; 22/04/2006 : Créé par Syl pour la version 2.5.
; 22/07/2006 : Ajout d'une durée de recharge et du bonus de vitalite pour la version 3.0.
; 24/06/2007 : Adapté par Syl pour la version 3.0 Béta 16.

[Objet_+]
	NomFR = Fourrure
	NomEN = Fur
	CheminImage = Mods\SylPack\
	Image = Objet_FourrureDAnimal1
	NomPlurielFR = Fourrures
	NomPlurielEN = Furs
	DescriptionFR = Permet de fabriquer un manteau avec de la laine.
	DescriptionEN = Used to make a cloak with wool.
	Secret = 1
	Superposable = 10
	Competence = 1
	DureeFabrication = 400
	PrixVente = 76
	Utilisable = 1
	UtilisationUnique = 1
	EffetAttaque = 34
	#+1 indique que l'on crée l'objet suivant.
	CreerObjet = +1
	PerteRessourceIndice = 5
	PerteRessourceQuantite = 14
	#La fourrure se trouve sur tous les animaux d'indice de race suivants.
	EquipementRace = 19
	EquipementRace = 20
	EquipementRace = 21
	EquipementRace = 22
	EquipementRace = 77
	DureeRecharge = 10

[Objet_+]
	NomFR = Manteau de fourure
	NomEN = Fur cloak
	CheminImage = Mods\SylPack\
	Image = Objet_FourrureDAnimal2
	NomPlurielFR = Manteaux de fourure
	NomPlurielEN = Fur cloaks
	DescriptionFR = Manteau épais qui protège du froid.
	DescriptionEN = Thick cloak which protect from cold.
	Secret = 1
	Epoque = 1
	Categorie = 2
	Competence = 2
	PrixRessources(5) = 14
	DureeFabrication = 800
	PrixVente = 266
	BonusEnergie = 20
	BonusVitalite = 0.1
	BonusArmure = 1
	FichierApparenceM = 07.bmp
	FichierApparenceF = 13.bmp
	BonusResistance(4) = 0.25