; Rajoute de nouveaux trésors : les talents.
; Version 1.
; 24/06/2007 : Créé par Syl pour la version 3.0 Béta 16.

[Objet_+]
	NomFR = Expert en construction
	NomEN = Skilled in construction
	NomEffetFR = Maîtrise de la construction
	NomEffetEN = Construction mastery
	Image = Expert en construction
	CheminImage = Mods\SylPack\Talents\
	Description = Augmente vos compétences dans ce domaine.
	Description = Increase your skills.
	Secret = 1
	Unique = 1
	Indestructible = 1
	Inseparable = 1
	Categorie = 1
	Competence = 1
	DureeFabrication = 600
	PrixVente = 600
	Utilisable = 1
	UtilisationUnique = 1
	CreerObjet = +
	BonusCompetencesSpeciales(1) = 20
	Duree = -1
	TresorRace = 0
	PrixTalents = 6
	EffetAnnulationImpossible = 1
	UtilisationAutomatique = 1

[Objet_+]
	NomFR = Expert en démolition
	NomEN = Skilled in destruction
	NomEffetFR = Maîtrise de la démolition
	NomEffetEN = Destruction mastery
	Image = Expert en demolition
	CheminImage = Mods\SylPack\Talents\
	Description = Augmente vos compétences dans ce domaine.
	Description = Increase your skills.
	Secret = 1
	Unique = 1
	Indestructible = 1
	Inseparable = 1
	Categorie = 1
	Competence = 1
	DureeFabrication = 800
	PrixVente = 800
	Utilisable = 1
	UtilisationUnique = 1
	CreerObjet = +
	BonusCompetencesSpeciales(2) = 20
	Duree = -1
	TresorRace = 0
	PrixTalents = 8
	EffetAnnulationImpossible = 1
	UtilisationAutomatique = 1

[Objet_+]
	NomFR = Expert en négociations
	NomEN = Skilled in negotiation
	NomEffetFR = Maîtrise de la négociation
	NomEffetEN = Negotiation mastery
	Image = Expert en negociation
	CheminImage = Mods\SylPack\Talents\
	Description = Augmente vos compétences dans ce domaine.
	Description = Increase your skills.
	Secret = 1
	Unique = 1
	Indestructible = 1
	Inseparable = 1
	Categorie = 1
	Competence = 1
	DureeFabrication = 900
	PrixVente = 900
	Utilisable = 1
	UtilisationUnique = 1
	CreerObjet = +
	BonusCompetencesSpeciales(4) = 20
	Duree = -1
	TresorRace = 0
	PrixTalents = 9
	EffetAnnulationImpossible = 1
	UtilisationAutomatique = 1

[Objet_+]
	NomFR = Expert en cultures
	NomEN = Skilled in harvest
	NomEffetFR = Maîtrise des cultures
	NomEffetEN = Harvest mastery
	Image = Expert en cultures
	CheminImage = Mods\SylPack\Talents\
	Description = Augmente vos compétences dans ce domaine.
	Description = Increase your skills.
	Secret = 1
	Unique = 1
	Indestructible = 1
	Inseparable = 1
	Categorie = 1
	Competence = 1
	DureeFabrication = 1100
	PrixVente = 1100
	Utilisable = 1
	UtilisationUnique = 1
	CreerObjet = +
	BonusCompetencesRessources(8) = 20
	BonusCompetencesRessources(10) = 20
	Duree = -1
	TresorRace = 0
	PrixTalents = 11
	EffetAnnulationImpossible = 1
	UtilisationAutomatique = 1

[Objet_+]
	NomFR = Expert en explosifs
	NomEN = Skilled in explosive
	NomEffetFR = Maîtrise des explosifs
	NomEffetEN = Explosive mastery
	Image = Expert en explosifs
	CheminImage = Mods\SylPack\Talents\
	Description = Augmente vos compétences dans ce domaine.
	Description = Increase your skills.
	Secret = 1
	Unique = 1
	Indestructible = 1
	Inseparable = 1
	Categorie = 1
	Competence = 1
	DureeFabrication = 1300
	PrixVente = 1300
	Utilisable = 1
	UtilisationUnique = 1
	CreerObjet = +
	BonusCompetencesObjets(15) = 20
	Duree = -1
	TresorRace = 0
	PrixTalents = 13
	EffetAnnulationImpossible = 1
	UtilisationAutomatique = 1

[Objet_+]
	NomFR = Expert en escrime
	NomEN = Skilled in fencing
	NomEffetFR = Maîtrise de l'escrime
	NomEffetEN = Fencing mastery
	Image = Expert en escrime
	CheminImage = Mods\SylPack\Talents\
	Description = Augmente vos compétences dans ce domaine.
	Description = Increase your skills.
	Secret = 1
	Unique = 1
	Indestructible = 1
	Inseparable = 1
	Categorie = 1
	Competence = 1
	DureeFabrication = 1700
	PrixVente = 1700
	Utilisable = 1
	UtilisationUnique = 1
	CreerObjet = +
	BonusCompetencesObjets(7) = 20
	BonusCompetencesObjets(8) = 20
	Duree = -1
	TresorRace = 0
	PrixTalents = 17
	EffetAnnulationImpossible = 1
	UtilisationAutomatique = 1

[Objet_+]
	NomFR = Expert en alchimie
	NomEN = Skilled in alchemy
	NomEffetFR = Maîtrise de l'alchimie
	NomEffetEN = Alchemy mastery
	Image = Expert en alchimie
	CheminImage = Mods\SylPack\Talents\
	Description = Augmente vos compétences dans ce domaine.
	Description = Increase your skills.
	Secret = 1
	Unique = 1
	Indestructible = 1
	Inseparable = 1
	Categorie = 1
	Competence = 1
	DureeFabrication = 2100
	PrixVente = 2100
	Utilisable = 1
	UtilisationUnique = 1
	CreerObjet = +
	BonusCompetencesRessources(19) = 20
	BonusCompetencesRessources(20) = 20
	BonusCompetencesObjets(26) = 20
	Duree = -1
	TresorRace = 0
	PrixTalents = 21
	EffetAnnulationImpossible = 1
	UtilisationAutomatique = 1

[Objet_+]
	NomFR = Expert en athlétisme
	NomEN = Skilled in athletics
	NomEffetFR = Maîtrise de l'athlétisme
	NomEffetEN = Athletics mastery
	Image = Expert en athletsime
	CheminImage = Mods\SylPack\Talents\
	Description = Augmente vos compétences dans ce domaine.
	Description = Increase your skills.
	Secret = 1
	Unique = 1
	Indestructible = 1
	Inseparable = 1
	Categorie = 1
	Competence = 1
	DureeFabrication = 2700
	PrixVente = 2700
	Utilisable = 1
	UtilisationUnique = 1
	CreerObjet = +
	BonusVitesse = 1
	Duree = -1
	TresorRace = 0
	PrixTalents = 27
	EffetAnnulationImpossible = 1
	UtilisationAutomatique = 1

[Objet_+]
	NomFR = Expert en élevage
	NomEN = Skilled in rearing
	NomEffetFR = Maîtrise de l'élevage
	NomEffetEN = Rearing mastery
	Image = Expert en elevage
	CheminImage = Mods\SylPack\Talents\
	Description = Augmente vos compétences dans ce domaine.
	Description = Increase your skills.
	Secret = 1
	Unique = 1
	Indestructible = 1
	Inseparable = 1
	Categorie = 1
	Competence = 1
	DureeFabrication = 2800
	PrixVente = 2800
	Utilisable = 1
	UtilisationUnique = 1
	CreerObjet = +
	BonusCompetencesRessources(5) = 20
	BonusCompetencesRessources(6) = 20
	BonusCompetencesObjets(27) = 20
	Duree = -1
	TresorRace = 0
	PrixTalents = 28
	EffetAnnulationImpossible = 1
	UtilisationAutomatique = 1

[Objet_+]
	NomFR = Expert en gastronomie
	NomEN = Skilled in kooking
	NomEffetFR = Maîtrise de la gastronomie
	NomEffetEN = Kooking mastery
	Image = Expert en gastronomie
	CheminImage = Mods\SylPack\Talents\
	Description = Augmente vos compétences dans ce domaine.
	Description = Increase your skills.
	Secret = 1
	Unique = 1
	Indestructible = 1
	Inseparable = 1
	Categorie = 1
	Competence = 1
	DureeFabrication = 2900
	PrixVente = 2900
	Utilisable = 1
	UtilisationUnique = 1
	CreerObjet = +
	BonusCompetencesRessources(7) = 20
	BonusCompetencesRessources(9) = 20
	BonusCompetencesRessources(11) = 20
	BonusCompetencesRessources(23) = 20
	Duree = -1
	TresorRace = 0
	PrixTalents = 29
	EffetAnnulationImpossible = 1
	UtilisationAutomatique = 1

[Objet_+]
	NomFR = Expert en protections
	NomEN = Skilled in protection
	NomEffetFR = Maîtrise des protections
	NomEffetEN = Protection mastery
	Image = Expert en protections
	CheminImage = Mods\SylPack\Talents\
	Description = Augmente vos compétences dans ce domaine.
	Description = Increase your skills.
	Secret = 1
	Unique = 1
	Indestructible = 1
	Inseparable = 1
	Categorie = 1
	Competence = 1
	DureeFabrication = 3100
	PrixVente = 3100
	Utilisable = 1
	UtilisationUnique = 1
	CreerObjet = +
	BonusCompetencesObjets(16) = 20
	BonusCompetencesObjets(17) = 20
	BonusCompetencesObjets(18) = 20
	BonusCompetencesObjets(19) = 20
	Duree = -1
	TresorRace = 0
	PrixTalents = 31
	EffetAnnulationImpossible = 1
	UtilisationAutomatique = 1

[Objet_+]
	NomFR = Expert en théologie
	NomEN = Skilled in theology
	NomEffetFR = Maîtrise en théologie
	NomEffetEN = Theology mastery
	Image = Expert en theologie
	CheminImage = Mods\SylPack\Talents\
	Description = Augmente vos compétences dans ce domaine.
	Description = Increase your skills.
	Secret = 1
	Unique = 1
	Indestructible = 1
	Inseparable = 1
	Categorie = 1
	Competence = 1
	DureeFabrication = 3600
	PrixVente = 3600
	Utilisable = 1
	UtilisationUnique = 1
	CreerObjet = +
	BonusCompetencesServices(2) = 20
	BonusCompetencesObjets(23) = 20
	BonusCompetencesObjets(28) = 20
	Duree = -1
	TresorRace = 0
	PrixTalents = 36
	EffetAnnulationImpossible = 1
	UtilisationAutomatique = 1

[Objet_+]
	NomFR = Expert en logistique
	NomEN = Skilled in logistics
	NomEffetFR = Maîtrise de la logistique
	NomEffetEN = Logistics mastery
	Image = Expert en logistique
	CheminImage = Mods\SylPack\Talents\
	Description = Augmente vos compétences dans ce domaine.
	Description = Increase your skills.
	Secret = 1
	Unique = 1
	Indestructible = 1
	Inseparable = 1
	Categorie = 1
	Competence = 1
	DureeFabrication = 4400
	PrixVente = 4400
	Utilisable = 1
	UtilisationUnique = 1
	CreerObjet = +
	BonusMaxRessources = 20
	Duree = -1
	TresorRace = 0
	PrixTalents = 44
	EffetAnnulationImpossible = 1
	UtilisationAutomatique = 1