; Ajoute une puissante robe de mage dans la guilde de magie.
; Version 2.
; 23/01/2006 : Créé par Syl pour la version 2.5.
; 24/06/2007 : Adapté par Syl pour la version 3.0 Béta 16.

[Objet_+]
	NomFR = Robe d'archimage
	NomEN = Archmage dress
	NomPlurielFR = Robes d'archimage
	NomPlurielEN = Archmage dress
	CheminImage = Mods\SylPack\
	Image = Objet_Robe dArchimage
	DescriptionFR = Habit de puissant lanceur de sorts.
	DescriptionEN = Powerfull spell caster dress.
	Epoque = 4
	Categorie = 2
	Competence = 20
	PrixRessources(5) = 20
	PrixRessources(25) = 4
	DureeFabrication = 2400
	FabricationBatiment = 29
	PrixVente = 900
	BonusCompetencesObjets(21) = 5
	BonusCompetencesObjets(22) = 5
	BonusCompetencesObjets(23) = 5
	FichierApparenceM = 29.bmp
	FichierApparenceF = 41.bmp
	BonusResistance(3) = 0.25
	BonusResistance(5) = 0.25
	BonusResistance(6) = 0.25