; Ajoute un trésor qui permet de gagner 20% d'investissement en 10 minutes.
; Version 2.
; 28/04/2006 : Créé par Syl pour la version 2.5.
; 24/06/2007 : Adapté par Syl pour la version 3.0 Béta 16.

[Objet_+]
	NomFR = Capitalisme
	NomEN = Capitalism
	NomEffetFR = Intérêts
	NomEffetEN = Interests
	CheminImage = Mods\SylPack\
	Image = Objet_Capitalisme
	NomPlurielFR = Capitalismes
	NomPlurielEN = capitalisms
	DescriptionFR = Permet d'investir de l'argent.
	DescriptionEN = Allow to invest money.
	TresorRace = 0
	Secret = 1
	Unique = 1
	Indestructible = 1
	Inseparable = 1
	Categorie = 1
	Competence = 1
	DureeFabrication = 600
	PrixVente = 600
	Utilisable = 1
	UtilisationUnique = 1
	EffetAttaque = 28
	CreerObjet = +0
	PerteArgent = 600
	GainArgent = 1.2
	Duree = 600
	PrixTalents = 12
	EffetAnnuleRestaureObjet = 1
	EffetAnnulationImpossible = 1
