; Ajoute une pelle dans l'atelier.
; Version 2.
; 25/03/2006 : Créé par Syl pour la version 2.5.
; 24/06/2007 : Adapté par Syl pour la version 3.0 Béta 16.

[Objet_+]
	NomFR = Pelle
	NomEN = Shovel
	NomPlurielFR = Pelles
	NomPlurielEN = Shovels
	CheminImage = Mods\SylPack\
	Image = Objet_Pelle
	DescriptionFR = Outil utilisé dans de nombreux travaux.
	DescriptionEN = Tool used for several works.
	Epoque = 2
	Categorie = 1
	Competence = 6
	PrixRessources(3) = 7
	PrixRessources(16) = 2
	DureeFabrication = 600
	#Indique le bâtiment dans lequel l'objet est fabriqué.
	FabricationBatiment = 10
	PrixVente = 190
	BonusAttaque = 6
	EffetAttaque = 12
	BonusCompetencesRessources(8) = 8
	BonusCompetencesRessources(10) = 8
	BonusCompetencesRessources(13) = 8
	BonusCompetencesRessources(15) = 8
	BonusCompetencesRessources(24) = 8