; Ajoute un nouveau peuple composé de golems.
; Version 3.
; 23/01/2006 : Créé par Syl pour la version 2.5.
; 19/06/2006 : Ajout d'une durée de recharge pour la version 3.0.
; 24/06/2007 : Adapté par Syl pour la version 3.0 Béta 16.

[Race_+]
	NomFR = Géogolem
	NomEN = Geogolem
	NomPlurielFR = Géogolems
	NomPlurielEN = Geogolems
	DescriptionFR = Golem géant composé de nombreux matériaux.
	DescriptionEN = Giant golem consisted by several materials.
	RestrictionFeminin = 1
	DefinirApparence = 1
	CheminApparence = .\Mods\SylPack\GeoGolems
	Largeur=96
	Hauteur=96
	CoefVie = 100
	CoefEnergie = 100
	CoefMagie = 100
	CoefMoral = 100
	Attaque = 120
	CoefAttaque = 2
	Defense = 60
	CoefDefense = 1
	VitesseRegenerationMagie = 0.0025
	Experience = 0
	CoefCompSpeciale(2) = 3
	EffetAttaque = 12
	Armure = 36
	Vitesse = 4
	Pietinement = 36
	Infatigable = 1
	Ressources(13) = 20
	#Ressources(14) = 20
	Ressources(15) = 20
	Ressources(16) = 20
	Ressources(17) = 20
	Ressources(18) = 20
	Ressources(24) = 20
	Ressources(25) = 20
	DepartSansRessources = 1
	IA_Temeraire = 1
	RestaurationComplete = 1
	IndiceBestiaire = +
	Statut = 14

[Effet_+]
	Nom = Cercle de pierre
	Fichier = .\Mods\SylPack\Effet_CercleDePierre
	Largeur = 96
	Hauteur = 96
	NombreEtapes = 5
	DureeEtape = 1
	Son = .\Mods\Earthquake1.wav

[Objet_+]
	NomFR = Géogolem
	NomEN = Geogolem
	CheminImage = Mods\SylPack\
	Image = Objet_GeoGolem
	NomPlurielFR = Géogolems
	NomPlurielEN = Geogolems
	DescriptionFR = Invoque un golem gigantesque.
	DescriptionEN = Summon a gigantic golem.
	Epoque = 5
	Categorie = 1
	Competence = 24
	PrixRessources(13) = 20
	#PrixRessources(14) = 20
	PrixRessources(15) = 20
	PrixRessources(16) = 20
	PrixRessources(17) = 20
	PrixRessources(18) = 20
	PrixRessources(24) = 20
	PrixRessources(25) = 20
	DureeFabrication = 15000
	FabricationBatiment = 38
	PrixVente = 10000
	Utilisable = 1
	UtilisationUnique = 1
	Experience = 50
	#Le "+" indique que l'on invoque la dernière créature entrée.
	Invocation = +
	Quantite = 0.2
	#Le "+" indique que l'effet d'invocation est de dernier entré.
	EffetAttaque = +
	PerteMagie = 100
	DureeRecharge = 100

[Peuple_+]
	Nom = Golems
	CheminImage = Mods\SylPack\
	Image = Peuple_Golems
	NombreMonstres = 5
	MonstreIndice(1) = 31
	MonstreChance(1) = 0.75
	MonstreIndice(2) = 72
	MonstreChance(2) = 0.5
	MonstreIndice(3) = 73
	MonstreChance(3) = 0.5
	MonstreIndice(4) = 80
	MonstreChance(4) = 0.5
	#Le "+" charge le dernier monstre entré.
	MonstreIndice(5) = +
	MonstreChance(5) = 0.5
	NomChateauFR = Usine Tectonique
	NomChateauEN = Tectonic factory
	ChateauMaxVie = 3000
	ChateauLargeur = 128
	ChateauHauteur = 128
	ChateauEntreePositionX = 0
	ChateauEntreePositionY = 0