; Rajoute une nouvelle race jouable : les lutins.
; Version 4.
; 28/03/2006 : Créé par Tot19.
; 21/04/2006 : Adapté et corrigé en fichier mod par Syl pour la version 2.5.
; 24/05/2006 : Ajout d'une image d'aperçu de la race.
; 24/06/2007 : Adapté par Syl pour la version 3.0 Béta 16.

#Attention à ce qu'une race jouable ait un indice fixe.
#Ici, on remplace la dryade par le lutin pour garder la valeur fixe.
#Sinon, on risque des problèmes avec la sauvegarde du personnage.
[Race_78]
	NomMFR = Lutin
	NomMEN = Imp
	NomFFR = Lutin
	NomFEN = Imp
	NomMPlurielFR = Lutins
	NomMPlurielEN = Imps
	NomFPlurielFR = Lutins
	NomFPlurielEN = Imps
	Jouable = 1
	DescriptionFR = Les lutins sont des esprits de la forêt. Ce sont des petits génies bienveillant et de nature tranquille et joyeuse. Malgré leurs très petite taille, grâce à leur fabuleux pouvoirs magiques. Ils sont des ennemis à ne pas sous-estimés et aussi de précieux alliers.
	DescriptionEN = Imps are forest spirits. They are little kindly genius, happy and tranquil. Despite they are very little, they have fabulous magic powers. If you face them, don’t underestimate them. Also they are invaluable allys.
	Portrait = Mods\SylPack\Lutins\Lutin.gif
	NombreCategoriesApparences = 3
	DossiersCategoriesF(1) = .\Mods\SylPack\Lutins\Apparences\Corps\LF
	DossiersCategoriesF(2) = .\Mods\SylPack\Lutins\Apparences\Cheveux\LF
	DossiersCategoriesF(3) = .\Mods\SylPack\Lutins\Apparences\Habits\LF
	DossiersCategoriesM(1) = .\Mods\SylPack\Lutins\Apparences\Corps\LM
	DossiersCategoriesM(2) = .\Mods\SylPack\Lutins\Apparences\Cheveux\LM
	DossiersCategoriesM(3) = .\Mods\SylPack\Lutins\Apparences\Habits\LM
	DefinirApparence = 0
	DefinirApparence = 0
	CheminApparenceM = .\Mods\SylPack\Lutins\Persos\LutinsM
	CheminApparenceF = .\Mods\SylPack\Lutins\Persos\LutinsF
	#Le personnage ne change pas d'apparence en cours de jeu.
	ApparenceVerouillee = 1
        CoefVie = 0.75
	CoefEnergie = 1
	CoefMoral = 1.25
        #CoefMagie = 2
	CoefMagie = 1.75
	CoefAttaque = 0.50
	#CoefDefense = 0.75
	CoefDefense = 1
	#VitesseRegenerationVie = 0.00025
	#VitesseRegenerationMagie = 0.0050
	VitesseRegenerationMagie = 0.0025
	Parole = 1
	Experience = 1
	Equiper = 1
	CoefCompSpeciale(3) = 1.25
        CoefCompSpeciale(4) = 1.25
        CoefCompRessource(1) = 1.25
	CoefCompRessource(14) = 0.75
        CoefCompRessource(3) = 0.75
        CoefCompRessource(20) = 1.25
	CoefCompRessource(13) = 0.75
	CoefCompRessource(15) = 0.75
	CoefCompRessource(11) = 1.25
	CoefCompRessource(24) = 0.75
	CoefCompRessource(26) = 0.75
	CoefCompObjet(18) = 0.5
	CoefCompObjet(7) = 1.5
	CoefCompObjet(10) = 0.5
	CoefCompObjet(11) = 0.5
	CoefCompObjet(21) = 0.75
        CoefCompObjet(20) = 1.25
	CoefCompObjet(22) = 0.5
	CoefCompObjet(23) = 1.5
	CoefCompObjet(13) = 1.25
	CoefCompObjet(15) = 0.5
        CoefCompObjet(16) = 1.5
        CoefCompObjet(18) = 0.5
        CoefCompObjet(25) = 0.75
        #CoefCompObjet(26) = 1.25
        CoefCompObjet(26) = 1.5
        CoefCompObjet(21) = 0.75
        EffetAttaque = 23
        Vitesse = 3
        NombreObjets = 2
	Objet(1) = 133
	Objet(2) = 121
	IA_Manger = 1
	IA_Selectionner = 1

	IA_Pacifique = 0
	DepartSansRessources = 0
	NombreEquipement = 0
	RestaurationComplete = 0
	Statut = 0
	Statut = 1

	#IndiceBestiaire = +

#[Peuple_8]
#	NombreMonstres = 7
#	MonstreIndice(6) = +
#	MonstreChance(6) = 0.5
#	MonstreIndice(7) = 79
#	MonstreChance(7) = 0.5