; Ajoute une nouvelle magie : la magie shamanique.
; Version 1.
; 15/08/2007 : Crée par Syl pour la version 3.0 Béta 16

[CompetenceObjet_MAGIESHAMANIQUE]
	SAVPerso = CompétenceObjetMAGIESHAMANIQUE
	NomFR = Magie shamanique
	NomEN = Shamanic magic

[Batiment_BOSQUET]
	NomFR = Bosquet
	NomEN = Grove
	Image = Bosquet
	CheminImage = .\Mods\Magie shamanique\
	CheminImageBouton = .\Mods\Magie shamanique\Boutons\
	MetierFR = Druide
	MetierEN = Druid
	DescriptionFR = Permet d'appeler des animaux.
	DescriptionEN = Allow to call animals.
	MaxVie = 750
	Niveau = 0
	NoEpoque = 1
	Largeur = 81
	Hauteur = 96
	EntreePositionX = 0
	EntreePositionY = 32
	MaxStock = 80
	NombreEtapeFabrication = 1
	Fabrique = 1

[Objet_+]
	NomFR = Appeler ours
	NomEN = Call bear
	CheminImage = Mods\Magie shamanique\
	Image = Objet_Ours
	NomPlurielFR = Appeler ours
	NomPlurielEN = Call bears
	DescriptionFR = Appel un ours unique à vos cotés.
	DescriptionEN = Call an unique bear near you.
	Epoque = 1
	Categorie = 1
	Competence = MAGIESHAMANIQUE
	PrixRessources(7) = 4
	DureeFabrication = 400
	FabricationBatiment = BOSQUET
	PrixVente = 232
	Utilisable = 1
	UtilisationUnique = 1
	Experience = 4.7
	Invocation = 77
	Quantite = 1
	QuantiteMax = 1
	DureeRecharge = 10

[Objet_+]
	NomFR = Appeler tigre
	NomEN = Call tiger
	CheminImage = Mods\Magie shamanique\
	Image = Objet_Tigre
	NomPlurielFR = Appeler tigres
	NomPlurielEN = Call tigers
	DescriptionFR = Appel un tigre unique à vos cotés.
	DescriptionEN = Call an unique tiger near you.
	Epoque = 2
	Categorie = 1
	Competence = MAGIESHAMANIQUE
	PrixRessources(6) = 12
	DureeFabrication = 400
	FabricationBatiment = BOSQUET
	PrixVente = 236
	Utilisable = 1
	UtilisationUnique = 1
	Experience = 4.7
	Invocation = 20
	Quantite = 1
	QuantiteMax = 1
	DureeRecharge = 10

[Objet_+]
	NomFR = Ours monté
	NomEN = Mounted bear
	Image = Objet_OursMonte
	CheminImage = Mods\Magie shamanique\
	NomPlurielFR = Ours montés
	NomPlurielEN = Mounted bears
	DescriptionFR = 
	DescriptionEN = 
	Epoque = 2
	Categorie = 10
	Competence = MAGIESHAMANIQUE
	PrixRessources(7) = 20
	PrixRessources(12) = 10
	DureeFabrication = 2400
	FabricationBatiment = BOSQUET
	PrixVente = 1392
	BonusAttaque = 10
	BonusDeplacement = 1
	FichierApparenceM = Ours.bmp
	FichierApparenceF = Ours.bmp
	CheminApparence = .\Images\Persos\Monstres\Ours\
	Monture = 1
	ApparenceDecalageXH = 0
	ApparenceDecalageYH = -12
	ApparenceDecalageXD = -2
	ApparenceDecalageYD = -10
	ApparenceDecalageXB = 0
	ApparenceDecalageYB = -12
	ApparenceDecalageXG = 2
	ApparenceDecalageYG = -10
	ApparenceAvantPlanH = 0
	ApparenceAvantPlanD = 0
	ApparenceAvantPlanB = 1
	ApparenceAvantPlanG = 0