[Fenetre_Partie]
;Section Partie.
BandeCampagne = "Campagne"
BandePersonnaliser = "Monde personnalisé"
BandeBataille = "Champ de bataille"
BandeScenario = "Charger scénario"
BandeSauvegarde = "Charger partie"
BandeMode2Joueurs = "Mode 2 joueurs"
BandeServeur = "Créer serveur"
BandeClient = "Rejoindre partie"

;Section Campagne.
CadreSelectionnerCampagne = "Sélectionnez une campagne"
CadreSelectionnerScenarioCampagne = "Sélectionnez un scénario"

;Section monde personnalisé.
CadreMonde = "Monde"
CadreCarte = "Carte"
EtiquetteMondeChoisir = "Charger"
EtiquetteMondeGenerer = "Générer"
EtiquetteMondeTaille = "Taille :"
EtiquetteMondeTerrain = "Relief :"
EtiquetteMondeRessources = "Ressources :"
EtiquetteMondeRessourcesDepart = "Ressources de départ :"
EtiquetteMondeEpoqueDepart = "Epoque de départ :"
EtiquetteMondeLargeur = "Largeur :"
EtiquetteMondeHauteur = "Hauteur :" 
EtiquetteMondeRessourcesNombre = "Ressources :"
EtiquetteMondeChangementEpoque = "Changement d'époque :"
EtiquetteMondeDifficulte = "Difficulté :"
EtiquetteMondeResurrectionsNombre = "Résurrections au château :"
EtiquetteMondeResurrectionsVitesse = "Vitesse de résurrection :"
CadreFiefs = "Peuples"
EtiquetteFiefsNombre = "Nombre de peuples :"
EtiquetteFiefsNumero = "N°"
EtiquetteFiefsNombreVillageois = "Nombre de villageois :"
BoutonFiefsEquilibrer = "Equilibrer les peuples"
EtiquetteFiefsPeuples = "Peuple :"
EtiquetteFiefsEquipes = "Equipe :"
EtiquetteAleatoire = "Aléatoire"
EtiquetteFiefsTotal = "Total : "

;Section champ de bataille.
CadreArmees = "Armées"
CadreArmee1 = "Armée alliée"
CadreArmee2 = "Armée adverse"
EtiquetteArmeeEquipe = "Equipe : "
EtiquetteArmeeNombre = "Nombre de soldats :"
EtiquetteArmeePeuple = "Peuple :"
EtiquetteArmeeEquipement = "Equipement :"

;Section scénario et sauvegarde.
CadreSelectionnerScenario = "Sélectionner une partie"

;Section Réseau.
CadreServeur = Serveur
EtiquetteAdresseEnLigne = Adresse en ligne :
EtiquetteNomSession = Nom de la session : 
EtiquetteNombreJoueursMax = Nombre de joueurs maximum :
ChoixJouerEnLigne1 = Réseau local
ChoixJouerEnLigne2 = Jouer en ligne
BoutonCreerServeur = Créer un serveur
BoutonFermerServeur = Fermer le serveur
CadreClient = Parties en cours
EtiquetteAdresseServeur = IP du serveur (facultative) :
BoutonRafraichirParties = Rafraichir
BoutonConnecterParties = Se connecter
BoutonDeconnecterParties = Se déconnecter
CadreParametresReseaux = Paramètres réseaux
EtiquettePseudoReseau = Votre pseudo :
EtiquetteAdresseIP = Votre adresse IP locale :
EtiquetteNumeroPort = Numéro de port :
EtiquetteServiceProvider = Service provider :
CadreInformationsReseaux = Informations
#EtiquetteInformationsReseaux1 = "Le moteur réseau de cette version est encore expérimental. De nombreuses options manquent, il est lent et encore instable."
#EtiquetteInformationsReseaux2 = "Avant de lancer une partie réseau, il est conseillé de faire une copie de sauvegarde de vos personnages. Merci de votre compréhension."
EtiquetteInformationsReseaux1 = "En réseau, vous jouez en mode confrontation. Vous et un autre joueur vous retrouvez seuls sur une carte. Il n'y a aucune règle de jeu."
EtiquetteInformationsReseaux2 = "Dès qu'un joueur est tué, il ressuscite à un autre endroit de la carte."
CadreDetailPersonnageReseau = Détails du personnage
CadreDetailPartieReseau = Détails de la partie
EtiquetteMessageReseau = Messages :
BoutonEnvoyerMessageReseau = Envoyer

;Section mode 2 joueurs.
CadreMode2J = "Mode 2 joueurs"
BoutonMode2JActiver = "Activer le mode 2 joueurs sur cet ordinateur."
BoutonMode2JSeparer = "Toujours maintenir les 2 écrans séparés."
CadreMode2JJoueur1 = "Joueur 1"
CadreMode2JJoueur2 = "Joueur 2"
EtiquetteMode2JImpossible = "Sélectionnez 2 personnages différents."
EtiquetteMode2JActive = "Mode 2J activé"
EtiquetteMode2JDesActive = "Mode 2J désactivé"
TitreMode2JIMpossible = "Attention"
MessageMode2JImpossible = "Le mode duo est impossible avec la résolution d'affichage actuelle."
EtiquetteReseauClient = "Client réseau"
EtiquetteReseauServeur = "Serveur réseau"
ListeMode2JJoueur1(1) = "Situé sur la partie gauche de l'écran."
ListeMode2JJoueur1(2) = "Utilise uniquement le clavier."
ListeMode2JJoueur1(3) = "Le pavé numérique sert à diriger le curseur."
ListeMode2JJoueur1(4) = ""0 inser" correspond au clique gauche de la souris."
ListeMode2JJoueur1(5) = ""Entr" correspond au clique droit de la souris."
ListeMode2JJoueur1(6) = "". Suppr" correspond au clique central de la souris."
ListeMode2JJoueur2(1) = "Situé sur la partie droite de l'écran."
ListeMode2JJoueur2(2) = "Utilise uniquement la souris."

;Section personnage.
BandeNouveauPersonnage = "Nouveau personnage"
BandeChargerPersonnage = "Charger personnage"

;Section nouveau personnage.
CadreCreerPersonnage = "Créez un nouveau personnage"
CadreNomPersonnage = "Nom :"
ErreurNomPersonnage1 = "Entrez un nom."
ErreurNomPersonnage2 = "Ce nom comporte un caractère incorrect."
ErreurNomPersonnage3 = "Un autre personnage possède déjà ce nom."
CadreRacePersonnage = "Race :"
CadreSexePersonnage = "Sexe :"
BoutonSexePersonnage1 = "&Masculin"
BoutonSexePersonnage2 = "&Féminin"
ErreurSexePersonnage = "Ce choix est imposé par votre race."
CadreValidationPersonnage = "Validation :"
CadreGenerationPersonnage = "Génération automatiquement de personnages :"
BoutonGenerationPersonnage1 = "Générer &1 personnage"
BoutonGenerationPersonnage2 = "Générer 1&0 personnage"
BoutonGenerationPersonnage3 = "Générer &50 personnages"

;Section charger personnage.
CadreSelectionnerPersonnage = "Sélectionnez un ou plusieurs personnages"
ImageCadenatOuvert = "Les données de ce personnage sont sécurisées"
ImageCadenatFerme = "Les données de ce personnage ne sont pas sécurisées"
EtiquetteIA = "IA"
EtiquetteIAInfoBulle = "Ce personnage utilise une intelligence artificielle"
BandeApparencePersonnage = "Apparence"
BandeAIPersonnage = "IA"
BoutonPersonnaliserApparencePersonnage = "Personnaliser"
ChoixPersonnaliserApparencePersonnage = "Personnalisée"
ChoixFixerApparencePersonnage = "Fixée"
ChoixIA1 = "Aucune"
ChoixIA2 = "Standard"
ChoixIA3 = "Scriptée"
BandeCompetencesPersonnage = "Compétences"
BandeBestiairePersonnage = "Bestiaire"
BandeTresorsPersonnage = "Trésors"

;Section Bouton commencer.
BoutonRetour = "&Retour"
BoutonJouer = "&Jouer"