[Interface]
;Fenêtres.
TitreFenetreInventaire = "Inventaire"
TitreFenetreAchat = "Acheter"
TitreFenetreVente = "Vendre"
TitreFenetreRessources = "Ressources"
TitreFenetreCaracteristiques = "Caractéristiques"
TitreFenetreCompetences = "Compétences"
TitreFenetreBestiaire = "Bestiaire"
TitreFenetreCarte = "Carte"
TitreFenetreObjectifs = "Objectifs"

;Frames par secondes.
FPSMessage=FPS : 

;Barres de statut.
BarresStatutSeuilMessage1 = "Auto restauration à#"
BarresStatutSeuilMessage2 = "#(Roulette souris)"

;Boutons construire.
BoutonDemolirEtiquette=Démolir maison (Suppr)

;Boutons d'information.
BoutonInfosInfoBulle1=Fenêtre Bâtiment (B)
BoutonInfosInfoBulle2=Fenêtre Ressources (R)
BoutonInfosInfoBulle3=Fenêtre Personnage (P)
BoutonInfosInfoBulle4=Fenêtre Compétences (T)
BoutonInfosInfoBulle5=Fenêtre Inventaire (I)
BoutonInfosInfoBulle6=Fenêtre Bestiaire (U)
BoutonInfosInfoBulle7=Carte (Tab)
BoutonInfosInfoBulle8=Menu / Pause (F10)
BoutonInfosInfoBulle9=Objectifs (F11)

;Boutons de menu.
BoutonMenuInfoBulle1=Sauvegarder le monde (F12)
BoutonMenuInfoBulle2=Quitter (Esc)

;Boutons déplacement.
BoutonDeplacementInfoBulle1=Rentrer au château (G)
BoutonDeplacementInfoBulle2=Rentrer à la maison (M)
BoutonDeplacementInfoBulle3=Chercher des herbes (F1)
BoutonDeplacementInfoBulle4=Chercher des pommes (F2)
BoutonDeplacementInfoBulle5=Chercher du bois (F3)
BoutonDeplacementInfoBulle6=Chercher de la pierre (F4)
BoutonDeplacementInfoBulle7=Chercher du fer (F5)
BoutonDeplacementInfoBulle8=Chercher des critaux (F6)
BoutonDeplacementInfoBulle9=Chercher de l'or (F7)
BoutonDeplacementInfoBulle10=Chercher du souffre (F8)
BoutonDeplacementInfoBulle11=Attaquer ennemi proche (W)
BoutonDeplacementInfoBulle12=Attaquer maison proche (X)
BoutonDeplacementInfoBulle13=Attaquer château proche (C)
BoutonDeplacementInfoBulle14=Ramasser un trésor (V)
BoutonDeplacementInfoBulle15=Mode automatique (A)
BoutonDeplacementInfoBulle16=Attaquer ses alliés (H)
BoutonDeplacementInfoBulle17=Stop (S)
BoutonDeplacementInfoBulle18=Changer la formation (F)
BoutonDeplacementInfoBulle19=En couverture (D)
BoutonDeplacementInfoBulle20=En attente (Z)
BoutonDeplacementInfoBulle21=En défense (L)
BoutonDeplacementInfoBulle22=En attaque (Q)
BoutonDeplacementInfoBulle23=En berserk (K)

;Boutons de raccourci objets.
BoutonRaccourciObjetEtiquette = "Equiper Objets "

MessageModeAutoMessage=Mode# Auto

NombreMessagesActions = 22
MessageAction1 = "En attente"
MessageAction2 = "Se déplacer"
MessageAction3 = "Récolter ressources"
MessageAction4 = "Aller à"
MessageAction5 = "Construire"
MessageAction6 = "Aller construire"
MessageAction7 = "En repos"
MessageAction8 = "Rentrer à la maison"
MessageAction9 = "Au travail"
MessageAction10 = "Entrer dans"
MessageAction11 = "Retourner château"
MessageAction12 = "Aller château"
MessageAction13 = "Aller trésor"
MessageAction14 = "Donner"
MessageAction15 = "Aller vendre"
MessageAction16 = "Attaquer"
MessageAction17 = "Détruire maison"
MessageAction18 = "Détruire château"
MessageAction19 = "Ressusciter"
MessageAction20 = "Fabriquer"
MessageAction21 = "Préparer Service"
MessageAction22 = "Au travail"

MessageConfirmationQuitter = "#     Voulez-vous vraiment quitter la partie ?"
MessageConfirmationAttaquer = "#  Voulez-vous vraiment attaquer vos alliés ?#  (Cette action vous rendera hostile à tout le# monde jusqu'à la mort de votre personnage)"
MessageConfirmationOui = "Oui (Entrée)"
MessageConfirmationNon = "Non (Echap)"