[Messages]

FichierConseil = "Info_Conseils.txt"
PrefixeConseil = "-"

Afficher=1

NombreMaxMessages=12

AfficherConseil=1
AfficherVie=1
AfficherBestiaire=1
AfficherArgent=1
AfficherRessources=1
AfficherObjets=1
AfficherSoldats=1
AfficherExperience=1
AfficherEmpereur=1

Duree=0.16
Couleur=&HFFFFFF

#PositionX=140
PositionX=60
PositionY=30

DecalageX=0
DecalageY=16

PrefixeMessage=-
PrefixeExperience=+

MessageVivant = "Vous êtes ressuscité."
MessageMort = "Vous êtes mort. Retournez au château ou trouvez un temple."
MessageArgent = "pièces d'argent."
MessageGain = "Vous avez gagné"
MessagePerte = "Vous avez perdu"
MessageBestiaire = "Vous avez vaincu"
MessageVie = "niveau supplémentaire à vos points de vie."
MessageEnergie = "niveau supplémentaire à vos points d'énergie."
MessageMagie = "niveau supplémentaire à vos points de magie."
MessageMoral = "niveau supplémentaire à vos points de moral."
MessageAttaque = "niveau supplémentaire à vos points d'attaque."
MessageDefense = "niveau supplémentaire à vos points de défense."
MessageSoldat = "soldat."
MessageSoldats = "soldats."
MessageCompetence = "niveau à la compétence"
MessageEmpereurVieM = " est devenu "
MessageEmpereurVieF = " est devenue "
MessageEmpereurMortM = " est mort"
MessageEmpereurMortF = " est morte"

MessageSauvegardeMonde = "- SAUVEGARDE DU MONDE TERMINEE !"
