; ************************************************************************************
; *                             Paramètres des services                              *
; ************************************************************************************

[Services]
NombreServices = 3

[Service_1]
	Nom = Aucun
	Description = Aucune
	VitesseCreation = 0
	TypeMatierePremiere = -1
	QuantiteMatierePremiere = 1
	Prix = 0
	Coefficient = 0
	NomCompetence = Aucun
	Effet = -1
	CoefExp = 0

[Service_2]
	Nom = Résurrection
	Description = On vous ressuscite instantanément.
	VitesseCreation = 0.25
	TypeMatierePremiere = -1
	QuantiteMatierePremiere = 1
	Prix = 200
	;Pourcentage de vie récupérée.
	Coefficient = 1
	NomCompetence = Prier
	Effet = 4
	CoefExp = 4

[Service_3]
	Nom = Primes de combat
	Description = Eliminez des adversaires pour gagner#de l'argent.
	VitesseCreation = 0
	TypeMatierePremiere = -1
	QuantiteMatierePremiere = 1
	Prix = 0
	;Ratio sur les primes perçues.
	Coefficient = 0.3
	NomCompetence = Percevoir des primes
	Effet = 9
	CoefExp = 0.15

;[Service_4]
	Nom = Préparer une chambre
	Description = Permet de bien se reposer.
	VitesseCreation = 0.1
	TypeMatierePremiere = -1
	QuantiteMatierePremiere = 1
	Prix = 100
	;Durée de repos.
	Coefficient = 120
	NomCompetence = Préparer des chambres
	Effet = -1