; ************************************************************************************
; *                             Paramètres des trésors                               *
; ************************************************************************************

[Tresors]
NombreTresors = 7

[Tresor_1]
	Nom = Pauvre trésor
	ValeurMin = 0
[Tresor_2]
	Nom = Petit trésor
	ValeurMin = 100
[Tresor_3]
	Nom = Trésor moyen
	ValeurMin = 300
[Tresor_4]
	Nom = Bon trésor
	ValeurMin = 600
[Tresor_5]
	Nom = Grand trésor
	ValeurMin = 1000
[Tresor_6]
	Nom = Super trésor
	ValeurMin = 3000
[Tresor_7]
	Nom = Trésor fabuleux
	ValeurMin = 6000