[Commentaires]
Afficher=1

Duree=16
DureeMin=0.1
DureeMax=0.2
DureeIntervale=0.01

Couleur=&HFFFFFF

DecalageX=24
DecalageY=-16

NombreTypeMessages=53
NombreMaxMessagesParType=18

[Commentaires_1]
;Travail terminée.
NombreMessages=17
Message(1)=Work complete.
Message(2)=FiNNishhedddd...
Message(3)=Finished.
Message(4)=Ready to take another job !
Message(5)=It's over.
Message(6)=I've finished...
Message(7)=This work is now over.
Message(8)=Very well, over.
Message(9)=Very well, it's finished.
Message(10)=At last, I've finished.
Message(11)=Good.
Message(12)=The job is over...
Message(13)=I've no work to do.
Message(14)=At last !
Message(15)=Finally !
Message(16)=It's fixed.
Message(17)=My work has been done !

[Commentaires_2]
;Matières premières épuisées.
NombreMessages=13
Message(1)=Damn it, I've no more raw material.
Message(2)=I must find some raw material.
Message(3)=I'm short of raw material.
Message(4)=I lack raw material.
Message(5)=No more raw material, I can't continue.
Message(6)=I need more raw material.
Message(7)=I get more raw material.
Message(8)=I have to get raw material.
Message(9)=I must find raw material.
Message(10)=I don't possess the necessary raw material.
Message(11)=I need to have a better supply in raw material.
Message(12)=I'm out of stock.
Message(13)=My stock has vanished.

[Commentaires_3]
;Coup critique.
NombreMessages=16
Message(1)=Critical strike !
Message(2)=Take this !
Message(3)=In your head.
Message(4)=Mega punch.
Message(5)=Super strike.
Message(6)=Strike !
Message(7)=And paf !
Message(8)=Vlan !
Message(9)=PAF !!!
Message(10)=And schtouck !
Message(11)=It hurts, don't you ?
Message(12)=I hit the bull's eye.
Message(13)=I hit a tender limb.
Message(14)=Chtoc.
Message(15)=Recolect yourself !
Message(16)=Boum !

[Commentaires_4]
;Echec critique.
NombreMessages=6
Message(1)=I've Missed !
Message(2)=Missed !
Message(3)=I missed again.
Message(4)=Oups.
Message(5)=Shit !
Message(6)=I miss him.

[Commentaires_5]
;Maison attaquée.
NombreMessages=7
Message(1)=My home is being attacking !
Message(2)=They attack my home !
Message(3)=I will lose my home.
Message(4)=They're beaking my house.
Message(5)=Leave my home alone !
Message(6)=My house will be razed !
Message(7)=My home is in danger !

[Commentaires_6]
;Maison Détruite.
NombreMessages=8
Message(1)=I lost my home.
Message(2)=Here, I'm homeless.
Message(3)=Ouaa my house.
Message(4)=I've lost everything.
Message(5)=I must build it again.
Message(6)=Oh noooo, my house.
Message(7)=Too late, I lost my home.
Message(8)=Bouuu, ma pretty residence...

[Commentaires_7]
;Messages à l'aide pour Attaquer un perso.
NombreMessages=5
Message(1)=Come to my help !
Message(2)=I need help !
Message(3)=Heeeelp !
Message(4)=He is far too strong.
Message(5)=Help me !!!

[Commentaires_8]
;Messages à l'aide pour Attaquer une maison.
NombreMessages=2
Message(1)=Destroy this city.
Message(2)=Blow up this building.

[Commentaires_9]
;Messages à l'aide pour attaquer une forteresse.
NombreMessages=2
Message(1)=Attack this stronghold.
Message(2)=This fortress has no place in this world.

[Commentaires_10]
;Messages à l'aide si en danger.
NombreMessages=9
Message(1)=Help !
Message(2)=I can't hold any longer !
Message(3)=Help me !
Message(4)=Mercy !
Message(5)=Mama, help !
Message(6)=Mama !!!
Message(7)=Heeeelp !
Message(8)=I will die !
Message(9)=Stop him !

[Commentaires_11]
;Messages de secours.
NombreMessages=5
Message(1)=I'm coming.
Message(2)=Banzaï !!!
Message(3)=Here, I come !!!
Message(4)=Courage !
Message(5)=Resist.

[Commentaires_12]
;Chateau attaqué.
NombreMessages=6
Message(1)=Alert !
Message(2)=The castle is under attack !
Message(3)=Protect the castle.
Message(4)=Come back in defense, quick !!!
Message(5)=Warning, return to castle !
Message(6)=Alarm, alarm !

[Commentaires_13]
;Chateau détruit.
NombreMessages=4
Message(1)=Our kingdom has been destroyed !
Message(2)=We are lost !
Message(3)=This is the end.
Message(4)=Noooooooooo !!!

[Commentaires_14]
;L'adversaire fuit.
NombreMessages=3
Message(1)=Coward !
Message(2)=Comme back here !
Message(3)=I will catch you.

[Commentaires_15]
;Message de remerciement d'avoir été aidé au combat.
NombreMessages=10
Message(1)=Thanks.
Message(2)=You save me !
Message(3)=Ouf.
Message(4)=Well done.
Message(5)=Wow.
Message(6)=You got him.
Message(7)=Congratulation !
Message(8)=Thanks boy !
Message(9)=What a good striker !
Message(10)=I can win alone.

[Commentaires_16]
;L'adversaire se planque dans un bâtiment.
NombreMessages=4
Message(1)=Get out of there !
Message(2)=Get out !
Message(3)=I can't see you anymore !
Message(4)=I know where you are.

[Commentaires_17]
;Réattaque de nouveau le même adversaire.
NombreMessages=2
Message(1)=Ha, ha !!
Message(2)= So, we meet again !

[Commentaires_18]
;Message de manque de points de vie.
NombreMessages=3
Message(1)=I'm in bad condition !
Message(2)=I must regain health points !
Message(3)=I'm hurt !


[Commentaires_19]
;Message de manque de points d'energie.
NombreMessages=6
Message(1)=I haven't got enough stamina points.
Message(2)=I'm too exhausted...
Message(3)=I can't take it any more.
Message(4)=I need rest.
Message(5)=I feel sick.
Message(6)=I cannot continue if I've nothing to eat.


[Commentaires_20]
;Message de manque de points de magie.
NombreMessages=6
Message(1)=I haven't got enough magicka points.
Message(2)=I'm short of magicka.
Message(3)=I've no more magicka.
Message(4)=I have a headache.
Message(5)=I need magicka.
Message(6)=I need magicka points.

[Commentaires_21]
;Message de manque de points de moral.
NombreMessages=2
Message(1)=I haven't got enough moral points.
Message(2)=My moral is too low.

[Commentaires_22]
;Message d'ordre d'arrêt aux troupes.
NombreMessages=3
Message(1)=Stop !
Message(2)=Halt !
Message(3)=Halt here !

[Commentaires_23]
;Message d'ordre de se mettre en formation.
NombreMessages=1
Message(1)=Come back here.

[Commentaires_24]
;Message d'ordre de suivre le chef.
NombreMessages=10
Message(1)=Advance !
Message(2)=Go there.
Message(3)=Go on.
Message(4)=Come on, gooo !
Message(5)=Everyone, go on !
Message(6)=Go !
Message(7)=Go, go, go !
Message(8)=Walk !
Message(9)=Follow me !
Message(10)=Together...

[Commentaires_25]
;Message d'ordre de protéger le chef.
NombreMessages=6
Message(1)=Defend me !
Message(2)=I'm under attack !
Message(3)=They attack me !
Message(4)=i'm in danger !
Message(5)=I want protection.
Message(6)=Cover me !

[Commentaires_26]
;Message d'ordre d'attaquer un adversaire. (pour 1 soldat)
NombreMessages=3
Message(1)=Kill him !
Message(2)=Finish him !
Message(3)=Attack him !

[Commentaires_27]
;Message d'ordre d'attaquer un adversaire. (pour plusieurs soldats)
NombreMessages=3
Message(1)=Kill him !
Message(2)=Finish him !
Message(3)=Attack him !

[Commentaires_28]
;Message d'ordre d'attaquer une maison. (pour 1 soldat)
NombreMessages=2
Message(1)=Raze this.
Message(2)=Destroy this.

[Commentaires_29]
;Message d'ordre d'attaquer une maison. (pour plusieurs soldats)
NombreMessages=2
Message(1)=Raze this.
Message(2)=Destroy this.

[Commentaires_30]
;Message d'ordre d'attaquer un chateau. (pour 1 soldat)
NombreMessages=4
Message(1)=Destroy this headquarter !
Message(2)=Attack this stronghold !
Message(2)=This castle must fall.
Message(3)=Final attack.

[Commentaires_31]
;Message d'ordre d'attaquer un chateau. (pour plusieurs soldats)
NombreMessages=4
Message(1)=Destroy this headquarter !
Message(2)=Attack this stronghold !
Message(2)=This castle must fall.
Message(3)=Final attack.

[Commentaires_32]
;Message de réponse du soldat aux ordres.
NombreMessages=3
Message(1)=Yes sir !
Message(2)=With pleasure sir !!!
Message(3)=At your command !

[Commentaires_33]
;Message où l'ordre n'est pas passé.
NombreMessages=4
Message(1)=...
Message(2)=Is someone listening ?
Message(3)=Nobody listen me.
Message(4)=Eeeooohhh.....

[Commentaires_34]
;Message que dit une invocation convoquée.
NombreMessages=3
Message(1)=Yes master ?
Message(2)=Master ?
Message(3)=I'm waiting your orders ?

[Commentaires_35]
;Message de manque de ressources pour attaquer.
NombreMessages=2
Message(1)=OUt of ammo.
Message(2)=I'm need ammo.

[Commentaires_36]
;Commentaires des drakes.
NombreMessages=15
Message(1)=Groumfff.
Message(2)=Gourda gourda !!
Message(3)=Rrrashh...
Message(4)=Grrach.
Message(5)=Reeesch !
Message(6)=Rrrreuh.
Message(7)=Grrréé.
Message(8)=Reumm.
Message(9)=Slaaarr.
Message(10)=Rarrrg.
Message(11)=Shleeeess...
Message(12)=Gueeeer.
Message(13)=Raguuue.
Message(14)=Blueuuurrr.
Message(15)=Urm Beuhhh !

[Commentaires_37]
;Message d'ordre de garder sa maison. (pour 1 soldat)
NombreMessages=3
Message(1)=Keep my home.
Message(2)=Protect my home.
Message(3)=Protect my home from foes.

[Commentaires_38]
;Message d'ordre de garder un personnage. (pour plusieurs soldats)
NombreMessages=3
Message(1)=Keep my home.
Message(2)=Protect my home.
Message(3)=Protect my home from foes.

[Commentaires_39]
;Message d'ordre de garder un personnage. (pour 1 soldat)
NombreMessages=4
Message(1)=Keep him safe.
Message(2)=Protect him.
Message(3)=Protect him from foes.
Message(4)=Guard him !

[Commentaires_40]
;Message d'ordre de garder un personnage. (pour plusieurs soldats)
NombreMessages=4
Message(1)=Keep him safe.
Message(2)=Protect him.
Message(3)=Protect him from foes.
Message(4)=Guard him !

[Commentaires_41]
;Message d'ordre de garder son château principal. (pour 1 soldat)
NombreMessages=2
Message(1)=Keep the castle.
Message(2)=Protect the heart of our city.

[Commentaires_42]
;Message d'ordre de garder son château principal. (pour plusieurs soldats)
NombreMessages=2
Message(1)=Keep the castle.
Message(2)=Protect the heart of our city.

[Commentaires_43]
;Message d'ordre de garder un château. (pour 1 soldat)
NombreMessages=2
Message(1)=Keep this castle.
Message(2)=Protect the heart of this city.

[Commentaires_44]
;Message d'ordre de garder un château. (pour plusieurs soldats)
NombreMessages=2
Message(1)=Keep this castle.
Message(2)=Protect the heart of this city.

[Commentaires_45]
;L'adversaire a utilisé une invocation.
NombreMessages=1
Message(1)=Your soldier is out !

[Commentaires_46]
;Le personnage n'a plus assez d'argent.
NombreMessages=3
Message(1)=I've not enough money.
Message(2)=Money, money...
Message(3)=I need money.

[Commentaires_47]
;Message de remerciement d'avoir reçu des objets.
NombreMessages=8
Message(1)=Thanks !
Message(2)=It will be useful.
Message(3)=It will be helpful.
Message(4)=Very well.
Message(5)=Cool ! 
Message(6)=SOoo kind.
Message(7)=Thanks my friend.
Message(8)=It's nice my friend.

[Commentaires_48]
;Message de manque de ressources pour utiliser un objet.
NombreMessages=4
Message(1)=I'm short of resources.
Message(2)=Noo, I've not enough resources !
Message(3)=I'm lack of resources.
Message(4)=Short of resources ... no effect.

[Commentaires_49]
;Commentaires des poules.
NombreMessages=6
Message(1)=Kot.
Message(2)=Kot kot.
Message(3)=Kot !
Message(4)=Kot ?
Message(5)=Kodak.
Message(6)=Kot kot kodak.

[Commentaires_50]
;Commentaires des vaches.
NombreMessages=4
Message(1)=Meuh.
Message(2)=Meuuuh.
Message(3)=Braaah !
Message(4)=Meuh meuh ?

[Commentaires_51]
;Commentaires des béliers.
NombreMessages=4
Message(1)=Bêêêeee.
Message(2)=Bêê ?
Message(3)=Bahh.
Message(4)=Béêêê !

[Commentaires_52]
;Commentaires des chiens.
NombreMessages=7
Message(1)=Wouf.
Message(2)=Arf ?
Message(3)=Grrr.
Message(4)=Waaaf !
Message(5)=Waf waf.
Message(6)=Wouf wouf !
Message(7)=Ouu uhh...

[Commentaires_53]
;Commentaires des chats.
NombreMessages=7
Message(1)=Miaou.
Message(2)=Miou ?
Message(3)=Mmmm.
Message(4)=Meeeou !
Message(5)=Miou miou.
Message(6)=Miaou miaou !
Message(7)=Muuu...
