; ************************************************************************************
; *                            Paramètres des compétences                            *
; ************************************************************************************

[Competences_Speciales]
NombreCompetencesSpeciales = 4
CompetencesSpeciales1 = "Constuct building"
CompetencesSpeciales2 = "Raze building"
CompetencesSpeciales3 = "Critical strike"
CompetencesSpeciales4 = "Mercantile"