[Fenetre_Partie]
;Section Partie.
BandeCampagne      = "     Campaign    "
BandePersonnaliser = "  Custom world   "
BandeBataille      = "   Battlefield   "
BandeScenario      = "  Play scenario  "
BandeSauvegarde    = " Play saved game "
BandeMode2Joueurs  = " 2 players Mode  "
BandeServeur       = "   Host game   "
BandeClient        = "   Join game   "

;Section Campagne.
CadreSelectionnerCampagne = "Select campaign"
CadreSelectionnerScenarioCampagne = "Select scenario"

;Section monde personnalisé.
CadreMonde = "World" 
CadreCarte = "Map"
EtiquetteMondeChoisir = "Load"
EtiquetteMondeGenerer = "Generate"
EtiquetteMondeTaille = "Size :"
EtiquetteMondeTerrain = "Map :"
EtiquetteMondeRessources = "Resources :"
EtiquetteMondeEpoqueDepart = "Starting age :"
EtiquetteMondeLargeur = "Width :"
EtiquetteMondeHauteur = "Height :" 
EtiquetteMondeRessourcesNombre = "Resources :"
EtiquetteMondeRessourcesDepart = "Starting resources :"
EtiquetteMondeChangementEpoque = "Age advancement :"
EtiquetteMondeDifficulte = "Difficulty :"
EtiquetteMondeResurrectionsNombre = "Resurrections in castle :"
EtiquetteMondeResurrectionsVitesse = "Resurrection speed :"
CadreFiefs = "Nations"
EtiquetteFiefsNombre = "Number of nations :"
EtiquetteFiefsNumero = "N°"
EtiquetteFiefsNombreVillageois = "Population :"
BoutonFiefsEquilibrer = "Balance nations"
EtiquetteFiefsPeuples = "Race :"
EtiquetteFiefsEquipes = "Team :"
EtiquetteAleatoire = "Random"
EtiquetteFiefsTotal = "Total : "

;Section champ de bataille.
CadreArmees = "Armys"
CadreArmee1 = "Allied army"
CadreArmee2 = "Opposing army"
EtiquetteArmeeEquipe = "Team : "
EtiquetteArmeeNombre = "Number of soldiers :"
EtiquetteArmeePeuple = "Race :"
EtiquetteArmeeEquipement = "Equipment :"

;Section scénario et sauvegarde.
CadreSelectionnerScenario = "Select a game"

;Section Réseau.
CadreServeur = Servor
EtiquetteAdresseEnLigne = Address on line :
EtiquetteNomSession = Name of the session : 
EtiquetteNombreJoueursMax = Maximum number of players :
ChoixJouerEnLigne1 = LAN Game
ChoixJouerEnLigne2 = Play onLine
BoutonCreerServeur = Create a servor
BoutonFermerServeur = Close the servor
CadreClient = List of games
EtiquetteAdresseServeur = Servor IP (optional) :
BoutonRafraichirParties = Refresh
BoutonConnecterParties = Join game
BoutonDeconnecterParties = Disconnect
CadreParametresReseaux = Network parameters
EtiquettePseudoReseau = Your pseudo :
EtiquetteAdresseIP = Your local IP adress :
EtiquetteNumeroPort = Port number :
EtiquetteServiceProvider = Service provider :
CadreInformationsReseaux = Informations
#EtiquetteInformationsReseaux1 = "The network engine is a beta version. Many options are missing, he’s slow and unstable."
#EtiquetteInformationsReseaux2 = "Before playing a network game, save a backup of your characters. Thanks, and be patient."
EtiquetteInformationsReseaux1 = "Le network allow to play in confrontation mode. You and annother player can't meet in a map. There isn't any rule."
EtiquetteInformationsReseaux2 = "When a player is killed, he resurrects anywhere."
CadreDetailPersonnageReseau = Character informations
CadreDetailPartieReseau = Game informations
EtiquetteMessageReseau = Messages :
BoutonEnvoyerMessageReseau = Send

;Section mode 2 joueurs.
CadreMode2J = "2 players mode"
BoutonMode2JActiver = "Enable the 2 player mode ont this computer."
BoutonMode2JSeparer = "Always split the screen."
CadreMode2JJoueur1 = "Player 1"
CadreMode2JJoueur2 = "Player 2"
EtiquetteMode2JImpossible = "Select 2 different characters."
EtiquetteMode2JActive = "2P mode enabled"
EtiquetteMode2JDesActive = "2P mode disabled"
TitreMode2JIMpossible = "Warning"
MessageMode2JImpossible = "Two player mode is impossible with this screen resolution."
EtiquetteReseauClient = "Network client"
EtiquetteReseauServeur = "Network servor"
ListeMode2JJoueur1(1) = "On the left side of the screen."
ListeMode2JJoueur1(2) = "Use only the keyboard."
ListeMode2JJoueur1(3) = "The numeric paddle is used to move the cursor."
ListeMode2JJoueur1(4) = ""0 insert" is the left button of the mouse."
ListeMode2JJoueur1(5) = ""Enter" is the right button of the mouse."
ListeMode2JJoueur1(6) = "". Del" is the middle button of the mouse."
ListeMode2JJoueur2(1) = "On the right side of the screen."
ListeMode2JJoueur2(2) = "Use only the mouse"


;Section personnage.
BandeNouveauPersonnage = "New character"
BandeChargerPersonnage = "Load character"

;Section nouveau personnage.
CadreCreerPersonnage = "Create a new character"
CadreNomPersonnage = "Name :"
ErreurNomPersonnage1 = "Enter a name."
ErreurNomPersonnage2 = "Invalid letter."
ErreurNomPersonnage3 = "This name already exists."
CadreRacePersonnage = "Race :"
CadreSexePersonnage = "Gender :"
BoutonSexePersonnage1 = "&Male"
BoutonSexePersonnage2 = "&Female"
ErreurSexePersonnage = "This gender cannot be selected."
CadreValidationPersonnage = "Complete :"
CadreGenerationPersonnage = "Automatic Character's creation :"
BoutonGenerationPersonnage1 = "Create &1 character"
BoutonGenerationPersonnage2 = "Create 1&0 characters"
BoutonGenerationPersonnage3 = "Create &50 characters"

;Section charger personnage.
CadreSelectionnerPersonnage = "Select one or more characters"
ImageCadenatOuvert = "This character is protected"
ImageCadenatFerme = "This Character is not protected"
EtiquetteIA = "AI"
EtiquetteIAInfoBulle = "This character use an artificial intelligence"
BandeApparencePersonnage = "     Look     "
BandeAIPersonnage = "AI"
BoutonPersonnaliserApparencePersonnage = "Edit"
ChoixPersonnaliserApparencePersonnage = "Custom"
ChoixFixerApparencePersonnage = "Fix"
ChoixIA1 = "None"
ChoixIA2 = "Default"
ChoixIA3 = "Scripted"
BandeCompetencesPersonnage = "   Skills   "
BandeBestiairePersonnage = "Bestiary"
BandeTresorsPersonnage = "Treasures"

;Section Bouton commencer.
BoutonRetour = "&Back"
BoutonJouer = "&Play"