[Interface]
;Fenêtres.
TitreFenetreInventaire = "Inventory"
TitreFenetreAchat = "Buy"
TitreFenetreVente = "Sell"
TitreFenetreRessources = "Resources"
TitreFenetreCaracteristiques = "Caracteristics"
TitreFenetreCompetences = "Skills"
TitreFenetreBestiaire = "Bestiary"
TitreFenetreCarte = "Map"
TitreFenetreObjectifs = "Objectives"

;Frames par secondes.
FPSMessage=FPS : 

;Barres de statut.
BarresStatutSeuilMessage1 = "Self restauration#"
BarresStatutSeuilMessage2 = "#(Mouse wheel)"

;Boutons construire.
BoutonDemolirEtiquette=Blow up Building (Del)

;Boutons d'information.
BoutonInfosInfoBulle1=Buildings Window (B)
BoutonInfosInfoBulle2=Ressources Window (R)
BoutonInfosInfoBulle3=Character Window (P)
BoutonInfosInfoBulle4=Skills Window (T)
BoutonInfosInfoBulle5=Inventory Window (I)
BoutonInfosInfoBulle6=Bestiary Window (U)
BoutonInfosInfoBulle7=Map (Tab)
BoutonInfosInfoBulle8=Menu / Pause (F10)
BoutonInfosInfoBulle9=Game Goals (F11)

;Boutons de menu.
BoutonMenuInfoBulle1=Save the game (F12)
BoutonMenuInfoBulle2=Quit (Esc)

;Boutons déplacement.
BoutonDeplacementInfoBulle1=Return to castle (G)
BoutonDeplacementInfoBulle2=Return to house (M)
BoutonDeplacementInfoBulle3=Find Medecine herbs (F1)
BoutonDeplacementInfoBulle4=Find Apple (F2)
BoutonDeplacementInfoBulle5=Find Wood (F3)
BoutonDeplacementInfoBulle6=Find stone (F4)
BoutonDeplacementInfoBulle7=Find Iron (F5)
BoutonDeplacementInfoBulle8=Find Crystal (F6)
BoutonDeplacementInfoBulle9=Find Gold (F7)
BoutonDeplacementInfoBulle10=Find Sulfur (F8)
BoutonDeplacementInfoBulle11=Attack nearest ennemy (W)
BoutonDeplacementInfoBulle12=Attack nearest building (X)
BoutonDeplacementInfoBulle13=Attack nearest castle (C)
BoutonDeplacementInfoBulle14=Pick up treasure (V)
BoutonDeplacementInfoBulle15=Automatic mode (A)
BoutonDeplacementInfoBulle16=Attack ally (H)
BoutonDeplacementInfoBulle17=Stop (S)
BoutonDeplacementInfoBulle18=Change formation (F)
BoutonDeplacementInfoBulle19=Follow me (D)
BoutonDeplacementInfoBulle20=Stand by (Z)
BoutonDeplacementInfoBulle21=Protect area (L)
BoutonDeplacementInfoBulle22=Attack on sight (Q)
BoutonDeplacementInfoBulle23=Berserker (K)

;Boutons de raccourci objets.
BoutonRaccourciObjetEtiquette = "Equip item "

MessageModeAutoMessage=Auto# Mode

NombreMessagesActions = 22
MessageAction1 = "Waiting"
MessageAction2 = "Walking"
MessageAction3 = "Gathering resource"
MessageAction4 = "Going to"
MessageAction5 = "Building"
MessageAction6 = "Going to build"
MessageAction7 = "Resting"
MessageAction8 = "Going back to home"
MessageAction9 = "Working"
MessageAction10 = "Enter in"
MessageAction11 = "Going back to castle"
MessageAction12 = "Going to castle"
MessageAction13 = "Picking up treasure"
MessageAction14 = "Giving"
MessageAction15 = "Going to sell"
MessageAction16 = "Attacking"
MessageAction17 = "Razing building"
MessageAction18 = "Razing castle"
MessageAction19 = "Resurrecting"
MessageAction20 = "Making"
MessageAction21 = "Preparing service"
MessageAction22 = "Working"

MessageConfirmationQuitter = "#                        Quit the game ?"
MessageConfirmationAttaquer = "#          Do you want attack your allies ?#         (You become hostile to everyone #                       until your death)"
MessageConfirmationOui = "Yes (Enter)"
MessageConfirmationNon = "No (Escap)"