[Messages]

FichierConseil = "Info_Conseils.txt"
PrefixeConseil = "-"

Afficher=1

NombreMaxMessages=12

AfficherConseil=1
AfficherVie=1
AfficherBestiaire=1
AfficherArgent=1
AfficherRessources=1
AfficherObjets=1
AfficherSoldats=1
AfficherExperience=1
AfficherEmpereur=1

Duree=0.16
Couleur=&HFFFFFF

#PositionX=140
PositionX=60
PositionY=30

DecalageX=0
DecalageY=16

PrefixeMessage=-
PrefixeExperience=+

MessageVivant = "You bring back to life."
MessageMort = "You're dead. Come back to castle or come upon temple."
MessageArgent = "coins."
MessageGain = "You've recieved"
MessagePerte = "You've lost"
MessageBestiaire = "You've defeated"
MessageVie = "more point at the HEALTH level."
MessageEnergie = "more point at the STAMINA level."
MessageMagie = "more point at the MAGICKA level."
MessageMoral = "more point at the MORAL level."
MessageAttaque = "more point at the ATTACK level."
MessageDefense = "more point at the DEFENSE level."
MessageSoldat = "soldier."
MessageSoldats = "soldiers."
MessageCompetence = "level at the skill"
MessageEmpereurVieM = " become "
MessageEmpereurVieF = " become "
MessageEmpereurMortM = " is dead"
MessageEmpereurMortF = " is dead"

MessageSauvegardeMonde = "- WORLD SUCCESSFULLY SAVED !"
