; ************************************************************************************
; *                              Paramètres des époques                              *
; ************************************************************************************

[Epoques]
NombreEpoques = 5

[Epoque_1]
	Nom = Wood age
	BonusVieChateau = 0
	Duree = 0
	ChateauxRessourcesDepart = 0
	PersosRessourcesDepart = 0
	PersosArgentDepart = 100
	EmpereurNomM = Chief
	EmpereurNomF = Chief
	EmpereurPrix = 1000

[Epoque_2]
	Nom = Iron age
	BonusVieChateau = 500
	Duree = 5000
	ChateauxRessourcesDepart = 100
	PersosRessourcesDepart = 10
	PersosArgentDepart = 300
	EmpereurNomM = Lord
	EmpereurNomF = Lord
	EmpereurPrix = 1500

[Epoque_3]
	Nom = Ether age
	BonusVieChateau = 1000
	Duree = 10000
	ChateauxRessourcesDepart = 300
	PersosRessourcesDepart = 15
	PersosArgentDepart = 1000
	EmpereurNomM = Prince
	EmpereurNomF = Princess
	EmpereurPrix = 2500

[Epoque_4]
	Nom = Gold age
	BonusVieChateau = 1500
	Duree = 15000
	ChateauxRessourcesDepart = 500
	PersosRessourcesDepart = 20
	PersosArgentDepart = 1600
	EmpereurNomM = King
	EmpereurNomF = Queen
	EmpereurPrix = 4000

[Epoque_5]
	Nom = Imperial era
	BonusVieChateau = 2500
	Duree = 25000
	ChateauxRessourcesDepart = 800
	PersosRessourcesDepart = 20
	PersosArgentDepart = 2000
	EmpereurNomM = Emperor
	EmpereurNomF = Empress
	EmpereurPrix = 6000

[Epoque_6]
	Nom = Secret age
	BonusVieChateau = 4000
	Duree = 40000
	ChateauxRessourcesDepart = 800
	PersosRessourcesDepart = 20
	PersosArgentDepart = 2000
	EmpereurPrix = 10000

; ************************************************************************************
; *                      Paramètres des ressources de départ                         *
; ************************************************************************************

[RessourcesDeparts]
NombreRessourcesDeparts = 5

[RessourcesDepart_1]
	Nom = Nothing
	ChateauxRessourcesDepart = 0
	PersosRessourcesDepart = 0
	PersosArgentDepart = 0

[RessourcesDepart_2]
	Nom = Few
	ChateauxRessourcesDepart = 0
	PersosRessourcesDepart = 5
	PersosArgentDepart = 100

[RessourcesDepart_3]
	Nom = Average
	ChateauxRessourcesDepart = 100
	PersosRessourcesDepart = 10
	PersosArgentDepart = 300

[RessourcesDepart_4]
	Nom = Lot
	ChateauxRessourcesDepart = 300
	PersosRessourcesDepart = 15
	PersosArgentDepart = 1000

[RessourcesDepart_5]
	Nom = Maximize
	ChateauxRessourcesDepart = 500
	PersosRessourcesDepart = 20
	PersosArgentDepart = 1600

; ************************************************************************************
; *                      Paramètres des vitesses des époques                         *
; ************************************************************************************

[VitesseEpoques]
NombreVitesseEpoques = 5
VitesseEpoqueDefaut = 3

[VitesseEpoque_1]
Nom = Slower
Coef = 2

[VitesseEpoque_2]
Nom = Slow
Coef = 1.5

[VitesseEpoque_3]
Nom = Average
Coef = 1

[VitesseEpoque_4]
Nom = Fast
Coef = 0.5

[VitesseEpoque_5]
Nom = Faster
Coef = 0.25