; ************************************************************************************
; *                             Paramètres des services                              *
; ************************************************************************************

[Services]
NombreServices = 3

[Service_1]
	Nom = None
	Description = Nothing
	VitesseCreation = 0
	TypeMatierePremiere = -1
	QuantiteMatierePremiere = 1
	Prix = 0
	Coefficient = 0
	NomCompetence = None
	Effet = -1
	CoefExp = 0

[Service_2]
	Nom = Resurrection
	Description = Your are immediately ressurected.
	VitesseCreation = 0.25
	TypeMatierePremiere = -1
	QuantiteMatierePremiere = 1
	Prix = 200
	;Pourcentage de vie récupérée.
	Coefficient = 1
	NomCompetence = Pray
	Effet = 4
	CoefExp = 4

[Service_3]
	Nom = Battle bounts
	Description = Eliminate foes to earn money.
	VitesseCreation = 0
	TypeMatierePremiere = -1
	QuantiteMatierePremiere = 1
	Prix = 0
	;Ratio sur les primes perçues.
	Coefficient = 0.3
	NomCompetence = Collect bounts
	Effet = 9
	CoefExp = 0.15

;[Service_4]
	Nom = Prepare room
	Description = Your can quiet rest.
	VitesseCreation = 0.1
	TypeMatierePremiere = -1
	QuantiteMatierePremiere = 1
	Prix = 100
	;Durée de repos.
	Coefficient = 120
	NomCompetence = Prepare room
	Effet = -1