[Terrains]

TerrainOptimise=1

#Largeur d'une case du monde en pixels.
LargeurCase=16
HauteurCase=16

#Si le terrain est animé ou pas.
TerrainAnime=0
#Nombre d'animations pour les terrains dynamiques.
NombreEtapesAnimation=3

; ************************************************************************************
; *                             Paramètres des terrains                              *
; ************************************************************************************

NombreTypesTerrains=11

[Terrain_0]
	Nom=Plain
	CoefVitesse=1

[Terrain_1]
	Nom=Herbs
	CoefVitesse=1

[Terrain_2]
	Nom=Ground
	CoefVitesse=1

[Terrain_3]
	Nom=Desert
	CoefVitesse=0.75

[Terrain_4]
	Nom=Mountain
	CoefVitesse=0.5
	Inconstructible=1

[Terrain_5]
	Nom=Road
	CoefVitesse=1.25

[Terrain_6]
	Nom=Wall1
	CoefVitesse=0.75
	Inconstructible=1
[Terrain_7]
	Nom=Wall2
	CoefVitesse=0.2
	Inconstructible=1
[Terrain_8]
	Nom=Wall3
	CoefVitesse=0.2
	Inconstructible=1
[Terrain_9]
	Nom=Wall4
	CoefVitesse=0.2
	Inconstructible=1

[Terrain_10]
	Nom=Snow
	CoefVitesse=0.75

[Terrain_11]
	Nom=Water
	Effet=159
	CoefVitesse=0.5
	Animation=1
	Inconstructible=1
	ImgPersoDecalageX=0
	ImgPersoDecalageY=12

; ************************************************************************************
; *                              Paramètres des mondes                               *
; ************************************************************************************

[Mondes]
NombreTypesMondes=5
[Monde_1]
	Nom=Classic
	Relief=0.2
	SurfaceTerrain(1)=0
	SurfaceTerrain(2)=13

[Monde_2]
	Nom=Plains
	Relief=0.1
	SurfaceTerrain(1)=13
	SurfaceTerrain(2)=9
	SurfaceTerrain(3)=0
	SurfaceTerrain(4)=6
	SurfaceTerrain(11)=11
	Route=5

[Monde_3]
	Nom=Deserted
	Relief=0.7
	SurfaceTerrain(1)=0
	SurfaceTerrain(2)=0
	SurfaceTerrain(3)=9
	SurfaceTerrain(4)=0
	SurfaceTerrain(11)=4
	Route=2

[Monde_4]
	Nom=Mountainous
	Relief=0.08
	SurfaceTerrain(1)=8
	SurfaceTerrain(2)=8
	SurfaceTerrain(3)=8
	SurfaceTerrain(4)=18
	SurfaceTerrain(11)=6
	Route=5

[Monde_5]
	Nom=Large lakes
	Relief=0.2
	SurfaceTerrain(1)=13
	SurfaceTerrain(2)=9
	SurfaceTerrain(3)=0
	SurfaceTerrain(4)=5
	SurfaceTerrain(11)=13
	Route=5
