; ************************************************************************************
; *                             Paramètres des trésors                               *
; ************************************************************************************

[Tresors]
NombreTresors = 7

[Tresor_1]
	Nom = Poor treasure
	ValeurMin = 0
[Tresor_2]
	Nom = Small treasure
	ValeurMin = 100
[Tresor_3]
	Nom = medium treasure
	ValeurMin = 300
[Tresor_4]
	Nom = Good treasure
	ValeurMin = 600
[Tresor_5]
	Nom = Great treasure
	ValeurMin = 1000
[Tresor_6]
	Nom = Super treasure
	ValeurMin = 3000
[Tresor_7]
	Nom = Wonderful treasure
	ValeurMin = 6000