; Ajoute une nouvelle magie : la magie effigique.
; Version 1.
; 15/08/2007 : Crée par Syl pour la version 3.0 Béta 16

[CompetenceObjet_MAGIEEFFIGIQUE]
	SAVPerso = CompétenceObjetMAGIEEFFIGIQUE
	NomFR = Magie effigique
	NomEN = Effigic magic

[Batiment_ATELIERSCULPTURE]
	NomFR = Atelier de sculpture
	NomEN = Sculpture workshop
	Image = Atelier de sculpture
	CheminImage = .\Mods\Magie effigique\Images\Batiments\
	CheminImageBouton = .\Mods\Magie effigique\Images\Batiments\Boutons\
	MetierFR = Sculpteur
	MetierEN = Sculptor
	DescriptionFR = Permet d'ériger des effigies.
	DescriptionEN = Allow to raise effigies.
	PrixRessources(14) = 20
	MaxVie = 1500
	Niveau = 0
	NoEpoque = 2
	Largeur = 96
	Hauteur = 160
	EntreePositionX = 0
	EntreePositionY = 54
	MaxStock = 80
	NombreEtapeFabrication = 1
	Fabrique = 1

[Objet_+]
	NomFR = Projection revitalisante
	NomEN = Revitalize projection
	Image = Projection revitalisante
	NomPlurielFR = Projections revitalisantes
	NomPlurielEN = Revitalize projections
	CheminImage = Mods\Magie effigique\Images\Objets\
	DescriptionFR = Capacité spéciale.
	DescriptionEN = Special capacity.
	Secret = 1
	#Unique = 1
	Indestructible = 1
	Inseparable = 1
	Categorie = 1
	Competence = 23
	DureeFabrication = 2400
	PrixVente = 575
	Utilisable = 1
	Experience = 1.5
	Invocation = 89
	Quantite = 0.5
	EffetAttaque = 15
	PerteMagie = 15
	DureeRecharge = 20
	RechargesMultiples = 1
	#TresorRace = 0
	#PrixTalents = 78

[Race_+]
	NomFR = Petite effigie de vie
	NomEN = Small life effigy
	NomPlurielFR = Petites effigies de vie
	NomPlurielEN = Small life effigies
	DescriptionFR = 
	DescriptionEN = 
	RestrictionMasculin = 1
	DefinirApparence = 1
	CheminApparence = .\Mods\Magie effigique\Images\Persos\Petite effigie de vie
	Largeur=16
	Hauteur=32
	CoefVie = 1
	CoefMagie = 1.5
	CoefAttaque = 3
	CoefDefense = 1
	Armure = 20
	VitesseRegenerationMagie = 0.0025
	CoefCompObjet(23) = 2
	Equiper = 1
	Kamikaze = 1
	Vitesse = 0
	Volant = 0
	Infatigable = 1
	DepartSansRessources = 1
	Ressources(13) = 20
	BonusMaxRessources = 80
	IA_Berserk = 1
	IA_Incommandable = 1
	RestaurationComplete = 1
	NombreObjets = 1
	Objet(1) = +
	IndiceBestiaire = +
	EffetMort = 24
	Statut = 15

[Race_+]
	NomFR = Effigie de vie
	NomEN = Life effigy
	NomPlurielFR = Effigies de vie
	NomPlurielEN = Life effigies
	DescriptionFR = 
	DescriptionEN = 
	RestrictionMasculin = 1
	DefinirApparence = 1
	CheminApparence = .\Mods\Magie effigique\Images\Persos\Effigie de vie
	Largeur=32
	Hauteur=64
	CoefVie = 2
	CoefMagie = 3
	CoefAttaque = 6
	CoefDefense = 1
	Armure = 20
	VitesseRegenerationMagie = 0.0025
	CoefCompObjet(23) = 4
	Equiper = 1
	EffetAttaque = 24
	Kamikaze = 1
	Vitesse = 0
	Volant = 0
	Infatigable = 1
	DepartSansRessources = 1
	Ressources(13) = 40
	BonusMaxRessources = 80
	IA_Berserk = 1
	IA_Incommandable = 1
	RestaurationComplete = 1
	NombreObjets = 1
	Objet(1) = +
	IndiceBestiaire = +
	EffetMort = 24
	Statut = 15

[Race_+]
	NomFR = Grande effigie de vie
	NomEN = High life effigy
	NomPlurielFR = Grandes effigies de vie
	NomPlurielEN = High life effigies
	DescriptionFR = 
	DescriptionEN = 
	RestrictionMasculin = 1
	DefinirApparence = 1
	CheminApparence = .\Mods\Magie effigique\Images\Persos\Grande effigie de vie
	Largeur=32
	Hauteur=64
	CoefVie = 3
	CoefMagie = 4.5
	CoefAttaque = 9
	CoefDefense = 1
	Armure = 20
	VitesseRegenerationMagie = 0.0025
	CoefCompObjet(23) = 8
	Equiper = 1
	EffetAttaque = 24
	Kamikaze = 1
	Vitesse = 0
	Volant = 0
	Infatigable = 1
	DepartSansRessources = 1
	Ressources(13) = 60
	BonusMaxRessources = 80
	IA_Berserk = 1
	IA_Incommandable = 1
	RestaurationComplete = 1
	NombreObjets = 1
	Objet(1) = +
	IndiceBestiaire = +
	EffetMort = 24
	Statut = 15

[Objet_+]
	NomFR = Petite effigie de vie
	NomEN = Small life effigy
	Image = Petite effigie de vie
	CheminImage = Mods\Magie effigique\Images\Objets\
	NomPlurielFR = Petites effigies de vie
	NomPlurielEN = Small life effigies
	DescriptionFR = Permet d'installer une effigie qui rend la vie.
	DescriptionEN = Create an effigy which ressurect.
	Epoque = 2
	Categorie = 1
	Competence = MAGIEEFFIGIQUE
	PrixRessources(13) = 20
	DureeFabrication = 1575
	PrixVente = 700
	Utilisable = 1
	UtilisationUnique = 1
	Experience = 4
	Invocation = -2
	Quantite = 1
	EffetAttaque = 18
	DureeRecharge = 24
	RechargesMultiples = 1
	FabricationBatiment = ATELIERSCULPTURE

[Objet_+]
	NomFR = Effigie de vie
	NomEN = Life effigy
	Image = Effigie de vie
	CheminImage = Mods\Magie effigique\Images\Objets\
	NomPlurielFR = Effigies de vie
	NomPlurielEN = Life effigies
	DescriptionFR = Permet d'installer une effigie qui rend la vie.
	DescriptionEN = Create an effigy which ressurect.
	Epoque = 3
	Categorie = 1
	Competence = MAGIEEFFIGIQUE
	PrixRessources(13) = 40
	DureeFabrication = 3150
	PrixVente = 1400
	Utilisable = 1
	UtilisationUnique = 1
	Experience = 8
	Invocation = -1
	Quantite = 1
	EffetAttaque = 18
	DureeRecharge = 48
	RechargesMultiples = 1
	FabricationBatiment = ATELIERSCULPTURE

[Objet_+]
	NomFR = Grande effigie de vie
	NomEN = High life effigy
	Image = Grande effigie de vie
	CheminImage = Mods\Magie effigique\Images\Objets\
	NomPlurielFR = Grandes effigies de vie
	NomPlurielEN = High life effigies
	DescriptionFR = Permet d'installer une effigie qui rend la vie.
	DescriptionEN = Create an effigy which ressurect.
	Epoque = 4
	Categorie = 1
	Competence = MAGIEEFFIGIQUE
	PrixRessources(13) = 60
	DureeFabrication = 4725
	PrixVente = 2100
	Utilisable = 1
	UtilisationUnique = 1
	Experience = 4
	Invocation = -0
	Quantite = 1
	EffetAttaque = 18
	DureeRecharge = 36
	RechargesMultiples = 1
	FabricationBatiment = ATELIERSCULPTURE

[Race_+]
	NomFR = Petite effigie de mort
	NomEN = Small death effigy
	NomPlurielFR = Petites effigies de mort
	NomPlurielEN = Small death effigies
	DescriptionFR = 
	DescriptionEN = 
	RestrictionMasculin = 1
	DefinirApparence = 1
	CheminApparence = .\Mods\Magie effigique\Images\Persos\Petite effigie de mort
	Largeur=16
	Hauteur=32
	CoefVie = 1
	CoefMagie = 1.5
	CoefAttaque = 3
	CoefDefense = 1
	Armure = 20
	VitesseRegenerationMagie = 0.0025
	CoefCompObjet(23) = 2
	Equiper = 1
	Kamikaze = 1
	Vitesse = 0
	Volant = 0
	Infatigable = 1
	DepartSansRessources = 1
	Ressources(13) = 20
	BonusMaxRessources = 80
	IA_Berserk = 1
	IA_Incommandable = 1
	RestaurationComplete = 1
	NombreObjets = 1
	Objet(1) = 93
	IndiceBestiaire = +
	EffetMort = 24
	Statut = 15

[Race_+]
	NomFR = Effigie de mort
	NomEN = Death effigy
	NomPlurielFR = Effigies de mort
	NomPlurielEN = Death effigies
	DescriptionFR = 
	DescriptionEN = 
	RestrictionMasculin = 1
	DefinirApparence = 1
	CheminApparence = .\Mods\Magie effigique\Images\Persos\Effigie de mort
	Largeur=32
	Hauteur=56
	CoefVie = 2
	CoefMagie = 3
	CoefAttaque = 6
	CoefDefense = 1
	Armure = 20
	VitesseRegenerationMagie = 0.0025
	CoefCompObjet(23) = 4
	Equiper = 1
	EffetAttaque = 24
	Kamikaze = 1
	Vitesse = 0
	Volant = 0
	Infatigable = 1
	DepartSansRessources = 1
	Ressources(13) = 40
	BonusMaxRessources = 80
	IA_Berserk = 1
	IA_Incommandable = 1
	RestaurationComplete = 1
	NombreObjets = 1
	Objet(1) = 93
	IndiceBestiaire = +
	EffetMort = 24
	Statut = 15

[Race_+]
	NomFR = Grande effigie de mort
	NomEN = High death effigy
	NomPlurielFR = Grandes effigies de mort
	NomPlurielEN = High death effigies
	DescriptionFR = 
	DescriptionEN = 
	RestrictionMasculin = 1
	DefinirApparence = 1
	CheminApparence = .\Mods\Magie effigique\Images\Persos\Grande effigie de mort
	Largeur=32
	Hauteur=64
	CoefVie = 3
	CoefMagie = 4.5
	CoefAttaque = 9
	CoefDefense = 1
	Armure = 20
	VitesseRegenerationMagie = 0.0025
	CoefCompObjet(23) = 8
	Equiper = 1
	EffetAttaque = 24
	Kamikaze = 1
	Vitesse = 0
	Volant = 0
	Infatigable = 1
	DepartSansRessources = 1
	Ressources(13) = 60
	BonusMaxRessources = 80
	IA_Berserk = 1
	IA_Incommandable = 1
	RestaurationComplete = 1
	NombreObjets = 1
	Objet(1) =93
	IndiceBestiaire = +
	EffetMort = 24
	Statut = 15

[Objet_+]
	NomFR = Petite effigie de mort
	NomEN = Small death effigy
	Image = Petite effigie de mort
	CheminImage = Mods\Magie effigique\Images\Objets\
	NomPlurielFR = Petites effigies de mort
	NomPlurielEN = Small death effigies
	DescriptionFR = Permet d'installer une effigie qui sème la mort.
	DescriptionEN = Create an effigy which kill others.
	Epoque = 2
	Categorie = 1
	Competence = MAGIEEFFIGIQUE
	PrixRessources(13) = 20
	DureeFabrication = 1575
	PrixVente = 700
	Utilisable = 1
	UtilisationUnique = 1
	Experience = 4
	Invocation = -2
	Quantite = 1
	EffetAttaque = 18
	DureeRecharge = 24
	RechargesMultiples = 1
	FabricationBatiment = ATELIERSCULPTURE

[Objet_+]
	NomFR = Effigie de mort
	NomEN = Death effigy
	Image = Effigie de mort
	CheminImage = Mods\Magie effigique\Images\Objets\
	NomPlurielFR = Effigies de mort
	NomPlurielEN = Death effigies
	DescriptionFR = Permet d'installer une effigie qui sème la mort.
	DescriptionEN = Create an effigy which kill others.
	Epoque = 3
	Categorie = 1
	Competence = MAGIEEFFIGIQUE
	PrixRessources(13) = 40
	DureeFabrication = 3150
	PrixVente = 1400
	Utilisable = 1
	UtilisationUnique = 1
	Experience = 8
	Invocation = -1
	Quantite = 1
	EffetAttaque = 18
	DureeRecharge = 48
	RechargesMultiples = 1
	FabricationBatiment = ATELIERSCULPTURE

[Objet_+]
	NomFR = Grande effigie de mort
	NomEN = High death effigy
	Image = Grande effigie de mort
	CheminImage = Mods\Magie effigique\Images\Objets\
	NomPlurielFR = Grandes effigies de mort
	NomPlurielEN = High death effigies
	DescriptionFR = Permet d'installer une effigie qui sème la mort.
	DescriptionEN = Create an effigy which kill others.
	Epoque = 4
	Categorie = 1
	Competence = MAGIEEFFIGIQUE
	PrixRessources(13) = 60
	DureeFabrication = 4725
	PrixVente = 2100
	Utilisable = 1
	UtilisationUnique = 1
	Experience = 4
	Invocation = -0
	Quantite = 1
	EffetAttaque = 18
	DureeRecharge = 36
	RechargesMultiples = 1
	FabricationBatiment = ATELIERSCULPTURE

[Objet_+]
	NomFR = Projection incendiaire
	NomEN = Incendiary projection
	Image = Projection incendiaire
	NomPlurielFR = Projections incendiaires
	NomPlurielEN = Incendiary projections
	CheminImage = Mods\Magie effigique\Images\Objets\
	DescriptionFR = Capacité spéciale.
	DescriptionEN = Special capacity.
	Secret = 1
	#Unique = 1
	Indestructible = 1
	Inseparable = 1
	Categorie = 1
	Competence = 21
	DureeFabrication = 2400
	PrixVente = 575
	Utilisable = 1
	Experience = 1.5
	Invocation = 82
	Quantite = 0.5
	EffetAttaque = 15
	PerteMagie = 15
	DureeRecharge = 20
	RechargesMultiples = 1
	#TresorRace = 0
	#PrixTalents = 78

[Race_+]
	NomFR = Petite effigie de feu
	NomEN = Small fire effigy
	NomPlurielFR = Petites effigies de feu
	NomPlurielEN = Small fire effigies
	DescriptionFR = 
	DescriptionEN = 
	RestrictionMasculin = 1
	DefinirApparence = 1
	CheminApparence = .\Mods\Magie effigique\Images\Persos\Petite effigie de feu
	Largeur=16
	Hauteur=32
	CoefVie = 1
	CoefMagie = 1.5
	CoefAttaque = 3
	CoefDefense = 1
	Armure = 20
	VitesseRegenerationMagie = 0.0025
	CoefCompObjet(23) = 2
	Equiper = 1
	Kamikaze = 1
	Vitesse = 0
	Volant = 0
	Infatigable = 1
	DepartSansRessources = 1
	Ressources(13) = 20
	BonusMaxRessources = 80
	IA_Berserk = 1
	IA_Incommandable = 1
	RestaurationComplete = 1
	NombreObjets = 1
	Objet(1) = +
	IndiceBestiaire = +
	EffetMort = 24
	Statut = 15

[Race_+]
	NomFR = Effigie de feu
	NomEN = Fire effigy
	NomPlurielFR = Effigies de feu
	NomPlurielEN = Fire effigies
	DescriptionFR = 
	DescriptionEN = 
	RestrictionMasculin = 1
	DefinirApparence = 1
	CheminApparence = .\Mods\Magie effigique\Images\Persos\Effigie de feu
	Largeur=32
	Hauteur=48
	CoefVie = 2
	CoefMagie = 3
	CoefAttaque = 6
	CoefDefense = 1
	Armure = 20
	VitesseRegenerationMagie = 0.0025
	CoefCompObjet(23) = 4
	Equiper = 1
	EffetAttaque = 24
	Kamikaze = 1
	Vitesse = 0
	Volant = 0
	Infatigable = 1
	DepartSansRessources = 1
	Ressources(13) = 40
	BonusMaxRessources = 80
	IA_Berserk = 1
	IA_Incommandable = 1
	RestaurationComplete = 1
	NombreObjets = 1
	Objet(1) = +
	IndiceBestiaire = +
	EffetMort = 24
	Statut = 15

[Race_+]
	NomFR = Grande effigie de feu
	NomEN = High fire effigy
	NomPlurielFR = Grandes effigies de feu
	NomPlurielEN = High fire effigies
	DescriptionFR = 
	DescriptionEN = 
	RestrictionMasculin = 1
	DefinirApparence = 1
	CheminApparence = .\Mods\Magie effigique\Images\Persos\Grande effigie de feu
	Largeur=32
	Hauteur=96
	CoefVie = 3
	CoefMagie = 4.5
	CoefAttaque = 9
	CoefDefense = 1
	Armure = 20
	VitesseRegenerationMagie = 0.0025
	CoefCompObjet(23) = 8
	Equiper = 1
	EffetAttaque = 24
	Kamikaze = 1
	Vitesse = 0
	Volant = 0
	Infatigable = 1
	DepartSansRessources = 1
	Ressources(13) = 60
	BonusMaxRessources = 80
	IA_Berserk = 1
	IA_Incommandable = 1
	RestaurationComplete = 1
	NombreObjets = 1
	Objet(1) = +
	IndiceBestiaire = +
	EffetMort = 24
	Statut = 15

[Objet_+]
	NomFR = Petite effigie de feu
	NomEN = Small fire effigy
	Image = Petite effigie de feu
	CheminImage = Mods\Magie effigique\Images\Objets\
	NomPlurielFR = Petites effigies de feu
	NomPlurielEN = Small fire effigies
	DescriptionFR = Permet d'installer une effigie qui lance des flammes.
	DescriptionEN = Create an effigy which throw fire.
	Epoque = 2
	Categorie = 1
	Competence = MAGIEEFFIGIQUE
	PrixRessources(13) = 20
	DureeFabrication = 1575
	PrixVente = 700
	Utilisable = 1
	UtilisationUnique = 1
	Experience = 4
	Invocation = -2
	Quantite = 1
	EffetAttaque = 18
	DureeRecharge = 24
	RechargesMultiples = 1
	FabricationBatiment = ATELIERSCULPTURE

[Objet_+]
	NomFR = Effigie de feu
	NomEN = Fire effigy
	Image = Effigie de feu
	CheminImage = Mods\Magie effigique\Images\Objets\
	NomPlurielFR = Effigies de feu
	NomPlurielEN = Fire effigies
	DescriptionFR = Permet d'installer une effigie qui lance des flammes.
	DescriptionEN = Create an effigy which throw fire.
	Epoque = 3
	Categorie = 1
	Competence = MAGIEEFFIGIQUE
	PrixRessources(13) = 40
	DureeFabrication = 3150
	PrixVente = 1400
	Utilisable = 1
	UtilisationUnique = 1
	Experience = 8
	Invocation = -1
	Quantite = 1
	EffetAttaque = 18
	DureeRecharge = 48
	RechargesMultiples = 1
	FabricationBatiment = ATELIERSCULPTURE

[Objet_+]
	NomFR = Grande effigie de feu
	NomEN = High fire effigy
	Image = Grande effigie de feu
	CheminImage = Mods\Magie effigique\Images\Objets\
	NomPlurielFR = Grandes effigies feuvie
	NomPlurielEN = High fire effigies
	DescriptionFR = Permet d'installer une effigie qui lance des flammes.
	DescriptionEN = Create an effigy which throw fire.
	Epoque = 4
	Categorie = 1
	Competence = MAGIEEFFIGIQUE
	PrixRessources(13) = 60
	DureeFabrication = 4725
	PrixVente = 2100
	Utilisable = 1
	UtilisationUnique = 1
	Experience = 4
	Invocation = -0
	Quantite = 1
	EffetAttaque = 18
	DureeRecharge = 36
	RechargesMultiples = 1
	FabricationBatiment = ATELIERSCULPTURE

[Race_+]
	NomFR = Effigie supreme
	NomEN = Supreme effigy
	NomPlurielFR = Effigies supremes
	NomPlurielEN = Supreme effigies
	DescriptionFR = 
	DescriptionEN = 
	RestrictionMasculin = 1
	DefinirApparence = 1
	CheminApparence = .\Mods\Magie effigique\Images\Persos\Effigie supreme
	Largeur=96
	Hauteur=128
	CoefVie = 5
	CoefMagie = 7.5
	CoefAttaque = 12
	CoefDefense = 1
	Armure = 20
	VitesseRegenerationMagie = 0.0025
	CoefCompObjet(23) = 12
	Equiper = 1
	EffetAttaque = 24
	Kamikaze = 1
	Vitesse = 0
	Volant = 0
	Infatigable = 1
	DepartSansRessources = 1
	Ressources(13) = 100
	BonusMaxRessources = 80
	IA_Berserk = 1
	IA_Incommandable = 1
	RestaurationComplete = 1
	NombreObjets = 3
	Objet(1) = -6
	Objet(1) = 93
	Objet(1) = -3
	IndiceBestiaire = +
	EffetMort = 24
	Statut = 15

[Objet_+]
	NomFR = Effigie supreme
	NomEN = Supreme effigy
	Image = Effigie supreme
	CheminImage = Mods\Magie effigique\Images\Objets\
	NomPlurielFR = Effigies supremes
	NomPlurielEN = Supreme effigies
	DescriptionFR = Permet d'installer une effigie envoie pleins de sorts.
	DescriptionEN = Create an effigy which cast lots of spells.
	Epoque = 5
	Categorie = 1
	Competence = MAGIEEFFIGIQUE
	PrixRessources(13) = 100
	DureeFabrication = 7875
	PrixVente = 3500
	Utilisable = 1
	UtilisationUnique = 1
	Experience = 26.6
	Invocation = -0
	Quantite = 1
	EffetAttaque = 18
	DureeRecharge = 60
	RechargesMultiples = 1
	FabricationBatiment = ATELIERSCULPTURE