; ************************************************************************************
; *                             Paramètres des décors                                *
; ************************************************************************************

[Decors]

[Decor_1]
Nom=Bridge

[Decor_2]
Nom=Flag

[Decor_3]
Nom=Fountain

[Decor_4]
Nom=Tombstone