; ************************************************************************************
; *                          Paramètres des effets visuels                           *
; ************************************************************************************

[Effets]

[Effet_1]
	Nom = Punch

[Effet_2]
	Nom = Blade

[Effet_3]
	Nom = Light flame

[Effet_4]
	Nom = Fire Wall

[Effet_5]
	Nom = Resurrrect

[Effet_6]
	Nom = Flame thrower

[Effet_7]
	Nom = Scratch

[Effet_8]
	Nom = Explosion

[Effet_9]
	Nom = Tip

[Effet_10]
	Nom = Earn money

[Effet_11]
	Nom = Blaze

[Effet_12]
	Nom = Shock

[Effet_13]
	Nom = Shadow sphere

[Effet_14]
	Nom = Tornado

[Effet_15]
	Nom = Poison gas

[Effet_16]
	Nom = Axe strike

[Effet_17]
	Nom = Cure

[Effet_18]
	Nom = Stones

[Effet_19]
	Nom = Explosion 2

[Effet_20]
	Nom = Gretter scratch

[Effet_21]
	Nom = Skull

[Effet_22]
	Nom = Fire column

[Effet_23]
	Nom = Green sparkles

[Effet_24]
	Nom = Destruction

[Effet_25]
	Nom = Blue circle

[Effet_26]
	Nom = Devour

[Effet_27]
	Nom = Explosion 3

[Effet_28]
	Nom = Spend

[Effet_29]
	Nom = Lightning

[Effet_30]
	Nom = Shoot

[Effet_31]
	Nom = Flame

[Effet_32]
	Nom = Haste

[Effet_33]
	Nom = Bonus

[Effet_34]
	Nom = Tool

[Effet_35]
	Nom = Sphere

[Effet_36]
	Nom = Sphere 2

[Effet_37]
	Nom = Explosion 4

[Effet_38]
	Nom = Clic

[Effet_39]
	Nom = Mail

[Effet_40]
	Nom = Ice blast

[Effet_41]
	Nom = White blade

[Effet_42]
	Nom = Generation

[Effet_43]
	Nom = Music

[Effet_45]
	Nom = Mewing

[Effet_46]
	Nom = Darkness