; ************************************************************************************
; *                            Paramètres des batiments                              *
; ************************************************************************************

[Batiments]

[Batiment_1]
	Nom = Wheat farm
	MetierM = Farmer
	MetierF = Farmer
	Description = Make wheat
	
[Batiment_2]
	Nom = Barley farm
	MetierM = Farmer
	MetierF = Farmer
	Description = Make barley
	
[Batiment_3]
	Nom = Sawmill
	MetierM = Woodcutter
	MetierF = Woodcutter
	Description = Change wood into planks
	
[Batiment_4]
	Nom = Sheep pen
	MetierM = Shepherd
	MetierF = Shepherdess
	Description = Make wool
	
[Batiment_5]
	Nom = Ranch
	MetierM = Breeder
	MetierF = Breeder
	Description = Make livestock
	
[Batiment_6]
	Nom = Butcher's shop 
	MetierM = Butcher
	MetierF = Butcher
	Description = Change livestock into meat 
	
[Batiment_7]
	Nom = Baker's shop
	MetierM = Baker
	MetierF = Baker
	Description = Change wheat into bread
	
[Batiment_8]
	Nom = Bar
	MetierM = Barman
	MetierF = Waitress
	Description = Change barely into beer
	
[Batiment_9]
	Nom = Dress' shop
	MetierM = Tailor
	MetierF = Dressmaker
	Description = Make clothes and hats with wool
	
[Batiment_10]
	Nom = Workshop
	MetierM = Artisan
	MetierF = Artisane
	Description = Make tools with wood and iron
	
[Batiment_11]
	Nom = Adventurer'shop
	MetierM = Merchant
	MetierF = Merchant
	Description = Make battle equipment with wood and leather
	
[Batiment_12]
	Nom = Tannery
	MetierM = Tanner
	MetierF = Tanner
	Description = Change livestock'skin into leather
	
[Batiment_13]
	Nom = Shoemaker's shop
	MetierM = Shoemaker
	MetierF = Shoemaker
	Description = Make shoes and boots with leather and metal
	
[Batiment_14]
	Nom = Glove-shop
	MetierM = Glovemaker
	MetierF = Glovemaker
	Description = Make gloves with leather and metal
	
[Batiment_17]
	Nom = Stable
	MetierM = Rider
	MetierF = Rider
	Description = Train horses
	
[Batiment_18]
	Nom = Stone quarry
	MetierM = Miner
	MetierF = Miner
	Description = Change stone into bricks
	
[Batiment_19]
	Nom = Encampment
	MetierM = Mercenary
	MetierF = Mercenary
	Description = Earn money by fighting
	
[Batiment_20]
	Nom = Foundry
	MetierM = Founder
	MetierF = Founder
	Description = Change iron to cast iron
	
[Batiment_21]
	Nom = Smithy
	MetierM = Smith
	MetierF = Smith
	Description = Make hand to hand weapons with iron
	
[Batiment_22]
	Nom = Archer's shop
	MetierM = Archer
	MetierF = Archer
	Description = Make ranged weapon with iron
	
[Batiment_23]
	Nom = Armorer's shop
	MetierM = Armorer
	MetierF = Armorer
	Description = Make armors, shields and helmets with cast iron
	
[Batiment_24]
	Nom = Steelworks
	MetierM = Founder
	MetierF = Founder
	Description = Change lot of iron into steel
	
[Batiment_25]
	Nom = Parchment'shop
	MetierM = Parchmenter
	MetierF = Parchmenter
	Description = Change livestock'skin into parchment
	
[Batiment_26]
	Nom = Church
	MetierM = Priest
	MetierF = Priest
	Description = Resurrect instantaneous
	
[Batiment_27]
	Nom = Laboratory
	MetierM = Healer
	MetierF = Healer
	Description = Change lot of medicinal herbs into aid potions
	
[Batiment_28]
	Nom = Ether laboratory
	MetierM = Etherer
	MetierF = Etherer
	Description = Change lot of crystals into ether
	
[Batiment_29]
	Nom = Mage guild
	MetierM = Wizard
	MetierF = Wizard
	Description = Make sorcerers' fit with wool
	
[Batiment_30]
	Nom = Pyromagic school
	MetierM = Pyromage
	MetierF = Pyromage
	Description = Make destruction spell books with parchment and paper
	
[Batiment_31]
	Nom = Necropolis
	MetierM = Necromancer
	MetierF = Necromancer
	Description = Animate deads with parchment and paper
	
[Batiment_32]
	Nom = Aquavitae school
	MetierM = Clergyman
	MetierF = Clergywoman
	Description = Make healing spell books with parchment and paper
	
[Batiment_33]
	Nom = Paper mill
	MetierM = Stationer
	MetierF = Stationer
	Description = Change lot of wood into paper
	
[Batiment_34]
	Nom = Goldsmith's shop
	MetierM = Goldsmith
	MetierF = Goldsmith
	Description = Change lot of gold into cast gold
	
[Batiment_35]
	Nom = Cider's shop
	MetierM = Cider grower
	MetierF = Cider grower
	Description = Make cider
	
[Batiment_36]
	Nom = Jewellery
	MetierM = Jeweller
	MetierF = Jeweller
	Description = Make rings with cast iron
	
[Batiment_37]
	Nom = Arsenal
	MetierM = Pyrotechnist
	MetierF = Pyrotechnist
	Description = Make firearms with steel and sulphur
	
[Batiment_38]
	Nom = Tecto workshop
	MetierM = Tectomage
	MetierF = Tectomage
	Description = Make golem with various resources
	
[Batiment_39]
	Nom = Chaos guild
	MetierM = Anarchist
	MetierF = Anarchist
	Description = Prepare revolution
	
[Batiment_40]
	Nom = Order guild
	MetierM = Inquisitor
	MetierF = Inquisitor
	Description = Keep harmony
	
[Batiment_41]
	Nom = Potions laboratory
	MetierM = Alchimist
	MetierF = Alchimist
	Description = Make magic potions with herbs, crystal and ether
	
[Batiment_42]
	Nom = Imperial smithy
	MetierM = Imperial Smith
	MetierF = Imperial Smith
	Description = Make imperial weapons
	
[Batiment_43]
	Nom = Imperial armorer's shop
	MetierM = Imperial armorer
	MetierF = Imperial armorer
	Description = Make imperial protections
	
[Batiment_44]
	Nom = Headquarters
	MetierM = Imperial general
	MetierF = Imperial general
	Description = Hire imperial troops
	
[Batiment_45]
	Nom = Dragon nest
	MetierM = Dragon father
	MetierF = Dragon mother
	Description = Hatch dragon eggs