; ************************************************************************************
; *                              Paramètres des peuples                              *
; ************************************************************************************

[Peuples]

[Peuple_1]
	Nom = Humans
	NomChateau = Castle
[Peuple_2]
	Nom = Animals
	NomChateau = Abandoned farm
[Peuple_3]
	Nom = Wild animals
	NomChateau = Jungle
[Peuple_4]
	Nom = Undeads
	NomChateau = Cemetery
[Peuple_5]
	Nom = Sorcerers
	NomChateau = Mage tower
[Peuple_6]
	Nom = Beastmen
	NomChateau = Beastmen's place
[Peuple_7]
	Nom = Technologists
	NomChateau = Research center
[Peuple_8]
	Nom = Sylvans
	NomChateau = Life tree
[Peuple_9]
	Nom = Plunders
	NomChateau = Plunders' camp
[Peuple_10]
	Nom = Imperials
	NomChateau = Imperial castle
[Peuple_11]
	Nom = Demons
	NomChateau = Abyssal donjon
[Peuple_12]
	Nom = Elementals
	NomChateau = Elemental cirlcle
[Peuple_13]
	Nom = Dragons
	NomChateau = Dragons cavern