; ************************************************************************************
; *                            Paramètres des résistances                            *
; ************************************************************************************

[Resistances]

[Resistance_1]
	Nom=Physical
	NomComplet=Physical resistance
	Attaque=Physical attack
	Abreviation=PH

[Resistance_2]
	Nom=Projectiles
	NomComplet=Projectiles resistance
	Attaque=Projectiles attack
	Abreviation=PR

[Resistance_3]
	Nom=Fire
	NomComplet=Fire resistance
	Attaque=Fire attack
	Abreviation=FI

[Resistance_4]
	Nom=Ice
	NomComplet=Ice resistance
	Attaque=Ice attack
	Abreviation=IC

[Resistance_5]
	Nom=Light
	NomComplet=Light resistance
	Attaque=Light attack
	Abreviation=LI

[Resistance_6]
	Nom=Death
	NomComplet=Death resistance
	Attaque=Death attack
	Abreviation=DE

[Resistance_7]
	Nom=Water
	NomComplet=Water resistance
	Attaque=Water attack
	Abreviation=WA

[Resistance_8]
	Nom=Electricity
	NomComplet=Electricity resistance
	Attaque=Electricity attack
	Abreviation=EL

[Statuts]

[Statut_1]
	Nom=Tiny
[Statut_2]
	Nom=Great
[Statut_3]
	Nom=Flammable
[Statut_4]
	Nom=Wet
[Statut_5]
	Nom=Animal
[Statut_6]
	Nom=undead
[Statut_7]
	Nom=Spirit
[Statut_8]
	Nom=Air spirit
[Statut_9]
	Nom=Fire spirit
[Statut_10]
	Nom=Water spirit
[Statut_11]
	Nom=Earth spirit
[Statut_12]
	Nom=Death spirit
[Statut_13]
	Nom=Dragon
[Statut_14]
	Nom=Artificial
[Statut_15]
	Nom=Machine