; ************************************************************************************
; *                              Paramètres des races                                *
; ************************************************************************************
[Races]
[Race_1]
	NomM = Human
	NomF = Human
	NomMPluriel = Humans
	NomFPluriel = Humans
	Description = Humans are the dominating race of the world. They haven't any disadvantage and got all average skills.

[Race_2]
	NomM = Dwarf
	NomF = Dwarf
	NomMPluriel = Dwarves
	NomFPluriel = Dwarves
	Description = Dwarves are the best blacksmiths. They know all metal secrets and making strongest weapons.

[Race_3]
	NomM = Elf
	NomF = Elf
	NomMPluriel = Elfs
	NomFPluriel = Elfs
	Description = Elfs are ones of the forest folks. They aren't robust but are very intelligent and control natural magic powers.

[Race_4]
	NomM = Half-elf
	NomF = Half-elf
	NomMPluriel = Half-elfs
	NomFPluriel = Half-elfs
	Description = Half-elfs are descended from elfs and humans. They’re less robust than humans but have magic power from elvish parents.

[Race_5]
	NomM = Colossus
	NomF = Colossus
	NomMPluriel = Colossus
	NomFPluriel = Colossus
	Description = Colossus are hill giants. They can’t adapt themselves to civilisation and surpass this by supernatural strength.

[Race_6]
	NomM = Kobold
	NomF = Kobold
	NomMPluriel = Kobolds
	NomFPluriel = Kobolds
	Description = Kobolds (alias foxmen) are known been tricky, kleptoman and craftsmen.

[Race_7]
	NomM = Feline
	NomF = Feline
	NomMPluriel = Felines
	NomFPluriel = Felines
	Description = Felines are half human and half animal. They are alive but less harden and prefer little luxuries than war.

[Race_8]
	Nom = Fairy
	NomPluriel = Fairies
	Description = Fairies are nature spirits. They are little but have uncommon magic powers.

[Race_9]
	NomM = Drake
	NomF = Drake
	NomMPluriel = Drakes
	NomFPluriel = Drakes
	Description = Drakes are dragon cousins. They have natural armor and can breath fire. Because they are reptile, they are unsociable with other races.

[Race_10]
	NomM = Garou
	NomF = Garou
	NomMPluriel = Garous
	NomFPluriel = Garous
	Description = Garous can transform themselves into giant wolves at will.

[Race_11]
	Nom = Shadow
	NomPluriel = Shadows
	Description = Shadows are partial etheral. Even if their body was consuming by black magic, their power are still powerful.

[Race_12]
	NomM = Celest
	NomF = Celest
	NomMPluriel = Celests
	NomFPluriel = Celests
	Description = Celests are winged people who are leaving their world to living with humans. Living on ground is painful but it eases by using spiritual gift.

[Race_13]
	Nom = Chicken
	NomPluriel = Chickens
	Description = .

[Race_14]
	Nom = Cow
	NomPluriel = Cows
	Description = .

[Race_15]
	Nom = Ram
	NomPluriel = Rams
	Description = .

[Race_16]
	Nom = Dog
	NomPluriel = Dogs
	Description = .

[Race_17]
	Nom = Horse
	NomPluriel = Horses
	Description = .

[Race_18]
	Nom = Rat
	NomPluriel = Rats
	Description = .

[Race_19]
	Nom = Wolf
	NomPluriel = Wolves
	Description = .

[Race_20]
	Nom = Tiger
	NomPluriel = Tigers
	Description = .

[Race_21]
	Nom = Lion
	NomPluriel = Lions
	Description = .

[Race_22]
	Nom = White tiger
	NomPluriel = White tigers
	Description = .

[Race_23]
	Nom = Skeleton
	NomPluriel = Skeletons
	Description = .

[Race_24]
	Nom = Zombie
	NomPluriel = Zombies
	Description = .

[Race_25]
	Nom = Ghost
	NomPluriel = Ghosts
	Description = .

[Race_26]
	Nom = Spectr
	NomPluriel = Spectrs
	Description = .

[Race_27]
	Nom = Vampire
	NomPluriel = Vampires
	Description = .

[Race_28]
	Nom = Dummy
	NomPluriel = Dummy
	Description = .

[Race_29]
	Nom = Familiar
	NomPluriel = Familiars
	Description = .

[Race_30]
	Nom = Acolyte
	NomPluriel = Acolytes
	Description = .

[Race_31]
	Nom = Stone golem
	NomPluriel = Stone golems
	Description = .

[Race_32]
	Nom = Arch-mage
	NomPluriel = Arch-mages
	Description = .

[Race_33]
	Nom = Frogotaur
	NomPluriel = Frogotaurs
	Description = .

[Race_34]
	Nom = Pigotaur
	NomPluriel = Pigotaurs
	Description = .

[Race_35]
	Nom = Monkeyman
	NomPluriel = Monkeymen
	Description = .

[Race_36]
	Nom = Minotaur
	NomPluriel = Minotaurs
	Description = .

[Race_37]
	Nom = Horror
	NomPluriel = Horrors
	Description = .

[Race_38]
	Nom = Automaton
	NomPluriel = Automatons
	Description = .

[Race_39]
	Nom = Robot
	NomPluriel = Robots
	Description = .

[Race_40]
	Nom = Scientist
	NomPluriel = Scientists
	Description = .

[Race_41]
	Nom = Tank
	NomPluriel = Tanks
	Description = .

[Race_42]
	Nom = Airship
	NomPluriel = Airships
	Description = .

[Race_43]
	Nom = Pirate
	NomPluriel = Pirates
	Description = .

[Race_44]
	Nom = Viking
	NomPluriel = Vikings
	Description = .

[Race_45]
	Nom = Amazon
	NomPluriel = Amazons
	Description = .

[Race_46]
	Nom = Assassin
	NomPluriel = Assassins
	Description = .

[Race_47]
	Nom = Black knight
	NomPluriel = Black knights
	Description = .

[Race_48]
	Nom = Soldier
	NomPluriel = Soldiers
	Description = .

[Race_49]
	Nom = Knight
	NomPluriel = Knights
	Description = .

[Race_50]
	Nom = Horseman
	NomPluriel = Horsemen
	Description = .

[Race_51]
	Nom = Capitain
	NomPluriel = Capitains
	Description = .

[Race_52]
	Nom = General
	NomPluriel = Generals
	Description = .

[Race_53]
	Nom = Succub
	NomPluriel = Succubs
	Description = .

[Race_54]
	Nom = Demon
	NomPluriel = Demons
	Description = .

[Race_55]
	Nom = Major demon
	NomPluriel = Major demons
	Description = .

[Race_56]
	Nom = Arch-demon
	NomPluriel = Arch-demons
	Description = .

[Race_57]
	Nom = King demon
	NomPluriel = King demon
	Description = .

[Race_58]
	Nom = Air elemental
	NomPluriel = Air elementals
	Description = .

[Race_59]
	Nom = Water elemental
	NomPluriel = Water elementals
	Description = .

[Race_60]
	Nom = Earth elemental
	NomPluriel = Earth elementals
	Description = .

[Race_61]
	Nom = Fire elemental
	NomPluriel = Fire elementals
	Description = .

[Race_62]
	Nom = Death elemental
	NomPluriel = Death elementals
	Description = .

[Race_63]
	Nom = Flying dragon
	NomPluriel = Flying dragons

[Race_64]
	Nom = Baby dragon
	NomPluriel = Baby dragons
	Description = .
	
[Race_65]
	Nom = Green dragon
	NomPluriel = Green dragons
	Description = .
	
[Race_66]
	Nom = Blue dragon
	NomPluriel = Blue dragons
	Description = .
	
[Race_67]
	Nom = Elder dragon
	NomPluriel = Elder dragons
	Description = .
	
[Race_68]
	Nom = Skeleton dragon
	NomPluriel = Skeleton dragons
	Description = .
	
[Race_69]
	Nom = Angel
	NomPluriel = Angels
	Description = .
	
[Race_70]
	Nom = Soul hunter
	NomPluriel = Soul hunters
	Description = .
	
[Race_71]
	Nom = Crystal golem
	NomPluriel = Crystal golems
	Description = .
	
[Race_72]
	Nom = Iron golem
	NomPluriel = Iron golems
	Description = .
	
[Race_73]
	Nom = Steel golem
	NomPluriel = Steel golems
	Description = .
	
[Race_74]
	Nom = Rebel
	NomPluriel = Rebels
	Description = .
	
[Race_75]
	Nom = Paladin
	NomPluriel = Paladins
	Description = .
	
[Race_76]
	Nom = Bat
	NomPluriel = Bats
	Description = .
	
[Race_77]
	Nom = Bear
	NomPluriel = Bears
	Description = .
	
[Race_78]
	Nom = Dryad
	NomPluriel = Dryads
	Description = .
	
[Race_79]
	Nom = Licorn
	NomPluriel = Licorns
	Description = .
	
[Race_80]
	Nom = Golden golem
	NomPluriel = Golden golems
	Description = .
	
[Race_81]
	NomM = Centaur
	NomF = Centaur
	NomMPluriel = Centaurs
	NomFPluriel = Centaurs
	Description = They are half man and half horse. They are strong and fast but they can't assume several jobs.
	
[Race_82]
	Nom = Fire
	NomPluriel = Fires
	Description = .
	
[Race_83]
	Nom = Landmine
	NomPluriel = Landmines
	Description = .
	
[Race_84]
	Nom = Fireball
	NomPluriel = Fireballs
	Description = 
	
[Race_85]
	Nom = Arrow
	NomPluriel = Arrows
	Description = 
	
[Race_86]
	Nom = Canon bowlder
	NomPluriel = Canon bowlders
	Description = 
	
[Race_87]
	Nom = Stone
	NomPluriel = Stone
	Description = 
	
[Race_88]
	Nom = Bullet
	NomPluriel = Bullets
	Description = 
	
[Race_89]
	Nom = Life spirit
	NomPluriel = Life spirits
	Description = .

[Race_90]
	Nom = Ice orb
	NomPluriel = Ice orbs
	Description = 

[Race_91]
	Nom = Cat
	NomPluriel = Cat
	Description = Small domestic feline

[Race_92]
	Nom = Fox
	NomPluriel = Foxs
	Description = Small but crafty one.

[Race_93]
	Nom = Greater air Elémental
	NomPluriel = Greater air Elémentals
	Description = .

[Race_94]
	Nom = Greater water Elémental
	NomPluriel = Greater water Elémentals
	Description = .

[Race_95]
	Nom = Greater earth Elémental
	NomPluriel = Greater earth Elémentals
	Description = .

[Race_96]
	Nom = Greater fire Elémental
	NomPluriel = Greater fire Elémentals
	Description = .

[Race_97]
	Nom = Elite escorter
	NomPluriel = Elite escorters
	Description = .