; ************************************************************************************
; *                              Paramètres des objets                               *
; ************************************************************************************

[Objets]

[Objet_1]
	Nom = Working suit
	NomPluriel = Working suits
	Description = Basic suit.
	
[Objet_2]
	Nom = Luxury dress
	NomPluriel = Luxury dress
	Description = Middle-class dress.
	
[Objet_3]
	Nom = Hat
	NomPluriel = Hats
	Description = Asthetic hat.
	
[Objet_4]
	Nom = Axe
	NomPluriel = Axes
	Description = Used to cut tree.
	
[Objet_5]
	Nom = Hammer
	NomPluriel = Hammers
	Description = Used to build houses.
	
[Objet_6]
	Nom = Flail
	NomPluriel = Flails
	Description = Used to farming.
	
[Objet_7]
	Nom = Pick
	NomPluriel = Picks
	Description = Used to dig rocks and minerals.
	
[Objet_8]
	Nom = Club
	NomPluriel = Clubs
	Description = Hand to hand weapon.
	
[Objet_9]
	Nom = Stick
	NomPluriel = Sticks
	Description = Hand to hand weapon.
	
[Objet_10]
	Nom = Sling
	NomPluriel = Slings
	Description = Light ranged weapon.
	
[Objet_11]
	Nom = Leather jacket
	NomPluriel = Leather jackets
	Description = Light armor.
	
[Objet_12]
	Nom = Small shield
	NomPluriel = Small shields
	Description = Light shield.
	
[Objet_13]
	Nom = Dagger
	NomPluriel = Daggers
	Description = Light hand to hand weapon.
	
[Objet_14]
	Nom = Sword
	NomPluriel = Swords
	Description = Medium hand to hand weapon.
	
[Objet_15]
	Nom = halberd
	NomPluriel = halberds
	Description = Heavy hand to hand weapon.
	
[Objet_16]
	Nom = Two handed sword
	NomPluriel = Two handed swords
	Description = Heavy hand to hand weapon.
	
[Objet_17]
	Nom = Short bow
	NomPluriel = Short bows
	Description = Light ranged weapon.
	
[Objet_18]
	Nom = Long bow
	NomPluriel = Long bows
	Description = Medium ranged weapon.
	
[Objet_19]
	Nom = Crossbow
	NomPluriel = Crossbows
	Description = Heavy ranged weapon.
	
[Objet_20]
	Nom = Chainmail
	NomPluriel = Chainmails
	Description = Medium armor.

[Objet_21]
	Nom = Plates armor
	NomPluriel = Plates armors
	Description = Heavy armor.

[Objet_22]
	Nom = Shield
	NomPluriel = Shields
	Description = Medium shield.

[Objet_23]
	Nom = Tower shield
	NomPluriel = Tower shields
	Description = Heavy shield.

[Objet_24]
	Nom = Helmet
	NomPluriel = Helmets
	Description = Medium helmet.

[Objet_25]
	Nom = Full helmet
	NomPluriel = Full helmets
	Description = Heavy helmet.

[Objet_26]
	Nom = Mage robe
	NomPluriel = Mage robes
	Description = Spell casting cloth.

[Objet_27]
	Nom = Ceremony robe
	NomPluriel = Ceremony robes
	Description = Religious cloth.

[Objet_28]
	Nom = Black robe
	NomPluriel = Black robes
	Description = Evil cloth.

[Objet_29]
	Nom = Sorcery hat
	NomPluriel = Sorcery hats
	Description = Spell casting hat.

[Objet_30]
	Nom = Fire blast
	NomPluriel = Fire blasts
	Description = Hand to hand desctruction spell.

[Objet_31]
	Nom = Fire ball
	NomPluriel = Fire balls
	Description = Ranged destruction spell.

[Objet_32]
	Nom = Set fire
	NomPluriel = Set fire
	Description = Destrution spell efficient against bulding.
	
[Objet_33]
	Nom = Call fire element
	NomPluriel = Call fire element
	Description = Summon an elemental efficient against bulding.
	
[Objet_34]
	Nom = Death ray
	NomPluriel = Death rays
	Description = Death spell which can cause the death of the user.
	
[Objet_35]
	Nom = Animate deads
	NomPluriel = Deaths liveliness
	Description = 
	
[Objet_36]
	Nom = Animate deads II
	NomPluriel = Deaths liveliness II
	Description = 
	
[Objet_37]
	Nom = Call death element
	NomPluriel = Call death element
	Description = Summon a dangerous elemental.
	
[Objet_38]
	Nom = Partial helmet
	NomPluriel = Partial helmet
	Description = Light helmet.
	
[Objet_39]
	Nom = Bulk
	NomPluriel = Bulks
	Description = Medium hand to hand weapon.

[Objet_40]
	Nom = Battle axe
	NomPluriel = Battle axes
	Description = Heavy hand to hand weapon.
	
[Objet_41]
	Nom = Healing
	NomPluriel = Healing
	Description = Self healing spell.
	
[Objet_42]
	Nom = Other healing
	NomPluriel = Other healing
	Description = Other people healing spell.
	
[Objet_43]
	Nom = Resurrection
	NomPluriel = Resurrections
	Description = Other people resurrection spell.
	
[Objet_44]
	Nom = Stone golem
	NomPluriel = Stone golems
	Description = Summon a standart golem.
	
[Objet_45]
	Nom = Walking boots
	NomPluriel = Walking boots
	Description = Used to walk comfortably.
	
[Objet_46]
	Nom = Showy shoes
	NomPluriel = Showy shoes
	Description = Used to walk comfortably.
	
[Objet_47]
	Nom = Studed boots
	NomPluriel = Studed boots
	Description = Battle boots.
	
[Objet_48]
	Nom = Steel boots
	NomPluriel = Steel boots
	Description = Reinforced battle boots.
	
[Objet_49]
	Nom = War bow
	NomPluriel = War bows
	Description = Long ranged weapon.
	
[Objet_50]
	Nom = Heavy crossbow
	NomPluriel = Heavy crossbows
	Description = Heavy ranged weapon.
	
[Objet_51]
	Nom = Cap
	NomPluriel = Caps
	Description = Usual hat.
	
[Objet_52]
	Nom = Vitality
	NomPluriel = Vitalitys
	Description = Self restauring vitality.
	
[Objet_53]
	Nom = Sorcerer staff
	NomPluriel = Sorcerer staffs
	Description = Spell casters staff.
	
[Objet_54]
	Nom = Saber
	NomPluriel = Sabers
	Description = Medium hand to hand weapon.
	
[Objet_55]
	Nom = Jeweled two handed sword
	NomPluriel = Jeweled two handed swords
	Description = Heavy hand to hand weapon.
	
[Objet_56]
	Nom = Dragon egg
	NomPluriel = Dragon eggs
	Description = 
	
[Objet_57]
	Nom = Impérial shield
	NomPluriel = Impérial shields
	Description = Medium shield.
	
[Objet_58]
	Nom = Black armors
	NomPluriel = Black armors
	Description = Heavy chaos armor.
	
[Objet_59]
	Nom = Pike
	NomPluriel = Pikes
	Description = Short ranged weapon.
	
[Objet_60]
	Nom = Weaken dagger
	NomPluriel = Weaken daggers
	Description = Light hand to hand dagger.
	
[Objet_61]
	Nom = Dragon tooth
	NomPluriel = Dragon teeth
	Description = 
	
[Objet_62]
	Nom = Horned helmet
	NomPluriel = Horned helmets
	Description = Medium helmet.
	
[Objet_63]
	Nom = Demon crown
	NomPluriel = Demon crowns
	Description = Honorary headgear.
	
[Objet_64]
	Nom = Call angel
	NomPluriel = Call angel
	Description = Summon a healer angel.
	
[Objet_65]
	Nom = Knife
	NomPluriel = Knifes
	Description = Used to cut meat.
	
[Objet_66]
	Nom = Backbag
	NomPluriel = Backbags
	Description = Carry more resources.
	
[Objet_67]
	Nom = Call hunter
	NomPluriel = Call hunter
	Description = Call a fast hunter.
	
[Objet_68]
	Nom = Explosion
	NomPluriel = Explosions
	Description = Large radius destruction spell.
	
[Objet_69]
	Nom = Health ring
	NomPluriel = Health rings
	Description = Increase your health points.
	
[Objet_70]
	Nom = Endurance ring
	NomPluriel = Endurance rings
	Description = Increase your stamina points.
	
[Objet_71]
	Nom = Spirit ring
	NomPluriel = Spirit rings
	Description = Increase your magicka points.
	
[Objet_72]
	Nom = Bravery ring
	NomPluriel = Bravery rings
	Description = Increase your moral points.
	
[Objet_73]
	Nom = Working gloves
	NomPluriel = Working gloves
	Description = Used to manual works.
	
[Objet_74]
	Nom = Battle gloves
	NomPluriel = Battle gloves
	Description = Increase your hand to hand skills.
	
[Objet_75]
	Nom = Accuracy gloves
	NomPluriel = Accuracy gloves
	Description = Increase your ranged skills.
	
[Objet_76]
	Nom = Power gloves
	NomPluriel = Power gloves
	Description = Increase your damages.
	
[Objet_77]
	Nom = Studed gloves
	NomPluriel = Studed gloves
	Description = Increase your defense.
	
[Objet_78]
	Nom = Crystal golem
	NomPluriel = Crystal golems
	Description = Summon a golem which throw crytal tips.
	
[Objet_79]
	Nom = Iron golem
	NomPluriel = Iron golems
	Description = Summon a very resistant golem.
	
[Objet_80]
	Nom = Steel golem
	NomPluriel = Steel golems
	Description = Summon an almost invincible golem.
	
[Objet_81]
	Nom = Steel gloves
	NomPluriel = Steel gloves
	Description = Increase your death resistant.
	
[Objet_82]
	Nom = Rebellious pact
	NomPluriel = Rebellious pacts
	Description = Ente into an agreement with rebels.
	
[Objet_83]
	Nom = Inquisition pact
	NomPluriel = Inquisition pacts
	Description = 
	
[Objet_84]
	Nom = Pure armor
	NomPluriel = Pure armor
	Description = Heavy order armor.
	
[Objet_85]
	Nom = Lightning
	NomPluriel = Lightnings
	Description = Long ranged destruction spell.
	
[Objet_86]
	Nom = Ice orb
	NomPluriel = Ice orbs
	Description = Ranged ice spell.
	
[Objet_87]
	Nom = Suzerain ring
	NomPluriel = Suzerain rings
	Description = Increase the loyalty of your soldiers.
	
[Objet_88]
	Nom = Arquebus
	NomPluriel = Arquebuses
	Description = Light firearm.
	
[Objet_89]
	Nom = Scarlet robe
	NomPluriel = Scarlet robes
	Description = Pyro-mage cloth.
	
[Objet_90]
	Nom = Brocade
	NomPluriel = Brocardes
	Description = Rich textile embroid with goilden wires.
	
[Objet_91]
	Nom = Sulphur breath
	NomPluriel = Sulphur breaths
	Description = Special capacity.
	
[Objet_92]
	Nom = Wolf transformation
	NomPluriel = Wolf transformations
	Description = Special capacity.
	
[Objet_93]
	Nom = Spectral projection
	NomPluriel = Spectral projections
	Description = Special capacity.
	
[Objet_94]
	Nom = Mousquet
	NomPluriel = Mousquets
	Description = Medium firearm.
	
[Objet_95]
	Nom = Restauration
	NomPluriel = Restaurations
	Description = Special capacity.
	
[Objet_96]
	Nom = Fairy powder
	NomPluriel = Fairy powder
	Description = Special capacity.
	
[Objet_97]
	Nom = Wheelbarrow
	NomPluriel = Wheelbarrows
	Description =
	
[Objet_98]
	Nom = Bombards
	NomPluriel = Bombards
	Description = Very heavy artillery.
	
[Objet_99]
	Nom = Studed leather jacket
	NomPluriel = Studed leather jacket
	Description = Advanced light armor.
	
[Objet_100]
	Nom = Protection ring
	NomPluriel = Protection rings
	Description = Protect against the enemy attacks.
	
[Objet_101]
	Nom = Basket
	NomPluriel = Baskets
	Description =
	
[Objet_102]
	Nom = Blazing armor
	NomPluriel = Blazing armors
	Description = Heavy destruction armor.
	
[Objet_103]
	Nom = Battle flail
	NomPluriel = Battle flails
	Description = Heavy hand to hand weapon.
	
[Objet_104]
	Nom = White sword
	NomPluriel = White swords
	Description = Medium hand to hand weapon.
	
[Objet_105]
	Nom = War axe
	NomPluriel = War axes
	Description = Heavy hand to hand weapon.
	
[Objet_106]
	Nom = Equalizeur
	NomPluriel = Equalizeurs
	Description = Very heavy hand to hand weapon.
	
[Objet_107]
	Nom = Trident
	NomPluriel = Tridents
	Description = Short ranged weapon.
	
[Objet_108]
	Nom = Haubert
	NomPluriel = Hauberts
	Description = Full chainmail.
	
[Objet_109]
	Nom = Weaver machine
	NomPluriel = Weaver machines
	Description = 
	
[Objet_110]
	Nom = Life potion
	NomPluriel = Life potions
	Description = Used to self ressurect.
	
[Objet_111]
	Nom = Elvish bow
	NomPluriel = Elvish bows
	Description = legendary elvish bow.

[Objet_112]
	Nom = Mithril chainmail
	NomPluriel = Mithril chainmails
	Description = legendary dwarven armor.

[Objet_113]
	Nom = Sylvest orb
	NomEffet = Wood generation
	NomPluriel = Sylvest orbs
	Description = Resources generator.

[Objet_114]
	Nom = Harvest orb
	NomEffet = Cereal generation
	NomPluriel = Harvest orb
	Description = Resources generator.

[Objet_115]
	Nom = Mineral orb
	NomEffet = Mineral generation
	NomPluriel = Mineral orbs
	Description = Resources generator.

[Objet_116]
	Nom = Gem orb
	NomEffet = Gems generation
	NomPluriel = Gem orbs
	Description = Resources generator.

[Objet_117]
	Nom = Etheral orb
	NomEffet = Ether generation
	NomPluriel = Etheral orbs
	Description = Resources generator.

[Objet_118]
	Nom = Scholarship orb
	NomEffet = Books generation
	NomPluriel = Scholarship orbs
	Description = Resources generator.

[Objet_119]
	Nom = Noble seal
	NomPluriel = Noble seals
	Description = Right of nobility.

[Objet_120]
	Nom = Stone bulk
	NomPluriel = Stone bulks
	Description = Gigantic weapon.

[Objet_121]
	Nom = Fast boots
	NomPluriel = Fast boots
	Description = Allow to run very fat.

[Objet_122]
	Nom = Plentiful horn
	NomEffet = Abundance
	NomPluriel = Plentiful horns
	Description = Never be hungry.

[Objet_123]
	Nom = Magic bag
	NomPluriel = Magic bags
	Description = Carry more resources.

[Objet_124]
	Nom = Bats swarm
	NomPluriel = Bats swarms
	Description = Special capacity.
	
[Objet_125]
	Nom = Bewitched rod
	NomPluriel = Bewitched rods
	Description = Fulfill wishes.
	
[Objet_126]
	Nom = Sulphur throw
	NomPluriel = Sulphur throws
	Description = Special capacity.
	
[Objet_127]
	Nom = Advanced wolf transformation
	NomPluriel = Advanced wolf transformations
	Description = Special capacity.
	
[Objet_128]
	Nom = Alloy orb
	NomEffet = Alloy generation
	NomPluriel = Alloy orbs
	Description = Resources generator.
	
[Objet_129]
	Nom = Imperial conscription
	NomPluriel = Imperial conscriptions
	Description = Call imperial reinforcements.
	
[Objet_130]
	Nom = Cauldron
	NomPluriel = Cauldrons
	Description = 
	
[Objet_131]
	Nom = Crusade
	NomPluriel = Crusades
	Description = Mobilize troops in exchange for money.

[Objet_132]
	Nom = Smith mallet
	NomPluriel = Smith mallets
	Description = Essential tool for every blacksmith.

[Objet_133]
	Nom = Curative orb
	NomEffet = Medicinal herbs generation
	NomPluriel = Curative orbs
	Description = Resources generator.

[Objet_134]
	Nom = Skull breaker
	NomPluriel = Skull breakers
	Description = Increase fatal damages.

[Objet_135]
	Nom = Merchant cloth
	NomPluriel = Merchant clothes
	Description = 

[Objet_136]
	Nom = Feast orb
	NomEffet = Wine generation
	NomPluriel = Feast orbs
	Description = Resources generator.

[Objet_137]
	Nom = Golen diadem
	NomPluriel = Golen diadems
	Description = fairy jewel.

[Objet_138]
	Nom = Sulphur orb
	NomEffet = Sulphur generation
	NomPluriel = Sulphur orbs
	Description = Resources generator.

[Objet_139]
	Nom = Sharp fangs
	NomPluriel = Sharp fangs
	Description = Special capacity.

[Objet_140]
	Nom = Shadow cloak
	NomPluriel = Shadow cloaks
	Description = Protecting cloak.

[Objet_141]
	Nom = Prosperity orb
	NomEffet = Money generation
	NomPluriel = Prosperity orbs
	Description = Money generator.

[Objet_142]
	Nom = Regeneration ring
	NomPluriel = Regeneration rings
	Description = Restore health

[Objet_143]
	Nom = Spiritual orb
	NomEffet = Magicka generation
	NomPluriel = Spiritual orbs
	Description = Restore spirit.

[Objet_144]
	Nom = Fortune orb
	NomEffet = Money generation
	NomPluriel = Fortune orbs
	Description = Money generator.

[Objet_145]
	Nom = Golen golem
	NomPluriel = Golen golems
	Description = Summun a golem which restaure at sunshine.

[Objet_146]
	Nom = Licorne horn
	NomPluriel = Licorne horns
	Description = Allow to make a powerful pike.

[Objet_147]
	Nom = Call fire
	NomPluriel = Call fire
	Description = Summun a dangerous fire which attack everyone.

[Objet_148]
	Nom = Landmine
	NomPluriel = Landmines
	Description = Put an explosive mine on the ground.

[Objet_149]
	Nom = Rapidity
	NomEffet = Rapidity
	NomPluriel = Rapidity
	Description = Increase your speed for a short time.

[Objet_150]
	Nom = Strengh potion
	NomEffet = Strengh increased
	NomPluriel = Strengh potions
	Description = Increase your strengh for a short time.

[Objet_151]
	Nom = Resistance potion
	NomEffet = Resistance increased
	NomPluriel = Resistance potions
	Description = Increase your resistance for a short time.

[Objet_152]
	Nom = Wisdom potion
	NomEffet = Wisdom increased
	NomPluriel = Wisdom potion
	Description = Increase your intelligence for a short time.

[Objet_153]
	Nom = Charm potion
	NomEffet = Charm increased
	NomPluriel = Charm potions
	Description = Increase your charm for a short time.

[Objet_154]
	Nom = Mobile sawmill
	NomEffet = Planks manufacture
	NomPluriel = Mobile sawmills
	Description = Change 10 woods into planks.

[Objet_155]
	Nom = Mobile quarry
	NomEffet = Bricks manufacture
	NomPluriel = Mobile quarrys
	Description = Change 10 stone into bricks.

[Objet_156]
	Nom = Pearl spear
	NomPluriel = Pearl spears
	Description = Spear with a licorne horn.

[Objet_157]
	Nom = Call life spirit
	NomPluriel = Call life spirit
	Description = Summon a spirit which resurrect the deaths.

[Objet_158]
	Nom = Extinction amulet
	NomPluriel = Extinction amulets
	Description = Protect against fire.

[Objet_159]
	Nom = Water
	NomEffet = Wet
	NomPluriel = Water

[Objet_160]
	Nom = Death amulet
	NomPluriel = Death amulets
	Description = Slow down your heart and freeze your blood.

[Objet_161]
	Nom = Ice
	NomEffet = Icy
	NomPluriel = Ice

[Objet_162]
	Nom = Weaken poison
	NomEffet = Weak
	NomPluriel = Weaken poisons

[Objet_163]
	Nom = Mana reserve
	NomEffet = Mana stock
	NomPluriel = Mana reserves
	Description = Increase your magicka for a long time.

[Objet_164]
	Nom = Crystal dagger
	NomPluriel = Crystal daggers
	Description = Used to carry crystals.

[Objet_165]
	Nom = Fox
	NomPluriel = Foxes
	Description = Call a familiar which collects you treasures.

[Objet_166]
	Nom = Berserk
	NomEffet = Berserk
	NomPluriel = Berserks
	Description = Increase your strengh and you are very aggressive.

[Objet_167]
	Nom = Small cat
	NomPluriel = Small cats
	Description = Call a familiar

[Objet_168]
	Nom = Zone of darkness
	NomEffet = Darkness
	NomPluriel = Zone of darkness
	Description = All the opponents around you knocks less well.

[Objet_169]
	Nom = Feline Rave-up
	NomEffet = Festive spirit
	NomPluriel = Feline Raves-up
	Description = Increases your and friends vitality.

[Objet_170]
	Nom = Saddle horse
	NomPluriel = Saddle horses
	Description = Long journey horse.

[Objet_171]
	Nom = War horse
	NomPluriel = War horses
	Description = Battle horse.

[Objet_172]
	Nom = Purebred
	NomPluriel = Purebreds
	Description = Racehorse.

[Objet_173]
	Nom = Wings
	NomPluriel = Wings
	Description = Allow to fly.

[Objet_174]
	Nom = Halo
	NomPluriel = Halos
	Description = Increase your spirituality.

[Objet_175]
	Nom = Rebellion
	NomPluriel = Rebellions
	Description = Mobilize troops in exchange for money.

[Objet_176]
	Nom = Air elemental
	NomPluriel = Air elementals
	Description = Create fast air elementals.

[Objet_177]
	Nom = Water elemental
	NomPluriel = Water elementaux
	Description = Create water elementals.

[Objet_178]
	Nom = Moon strenght
	NomEffet = Moon strenght
	NomPluriel = Moon strenghts
	Description = Increase your caracteristics for a short time.

[Objet_179]
	Nom = Drop mines
	NomPluriel = Drop mines
	Description = Drop explosive mine on the ground.

[Objet_180]
	Nom = Levitation
	NomEffet = Levitation
	NomPluriel = Levitation
	Description = Allow to fly.

[Objet_181]
	Nom = Make ether
	NomEffet = Making ether
	NomPluriel = Make ether
	Description = change 30 cristals into 10 ether.

[Objet_182]
	Nom = Stone skin
	NomEffet = Stone skin
	NomPluriel = Stone skins
	Description = Increase your physical resistance.

[Objet_183]
	Nom = Fire immunity
	NomEffet = Fire immunity
	NomPluriel = Fire immunity
	Description = Maximize your fire resistance.