; ************************************************************************************
; *                            Paramètres des ressources                             *
; ************************************************************************************

[Ressources]

[Ressource_1]
	Nom = Medic herbs.
	NomCompetence = Harvest herbs

[Ressource_2]
	Nom = Apples
	NomCompetence = Gather apples

[Ressource_3]
	Nom = Wood
	NomCompetence = Chop wood

[Ressource_4]
	Nom = Planks
	NomCompetence = Saw planks

[Ressource_5]
	Nom = Wool
	NomCompetence = Shear sheeps

[Ressource_6]
	Nom = Livestock
	NomCompetence = Keep livestock

[Ressource_7]
	Nom = Meat
	NomCompetence = Carve meat

[Ressource_8]
	Nom = Wheat
	NomCompetence = Culture wheat

[Ressource_9]
	Nom = Bread
	NomCompetence = Bake bread

[Ressource_10]
	Nom = Barley
	NomCompetence = Culture barley

[Ressource_11]
	Nom = Beer
	NomCompetence = Brew beer

[Ressource_12]
	Nom = Leather
	NomCompetence = Tan leather

[Ressource_13]
	Nom = Stone
	NomCompetence = Quarry stone

[Ressource_14]
	Nom = Bricks
	NomCompetence = Carve bricks

[Ressource_15]
	Nom = Iron
	NomCompetence = Extract iron

[Ressource_16]
	Nom = Cast iron
	NomCompetence = Forge iron

[Ressource_17]
	Nom = Steel
	NomCompetence = Forge steel

[Ressource_18]
	Nom = Crystals
	NomCompetence = Quarry crystals

[Ressource_19]
	Nom = Aid potions
	NomCompetence = Make potions

[Ressource_20]
	Nom = Ether
	NomCompetence = Make ether

[Ressource_21]
	Nom = Parchment
	NomCompetence = Make parchment

[Ressource_22]
	Nom = Paper
	NomCompetence = Make paper

[Ressource_23]
	Nom = Cider
	NomCompetence = Press cider

[Ressource_24]
	Nom = Gold
	NomCompetence = Prospect gold

[Ressource_25]
	Nom = Cast gold
	NomCompetence = Forge gold

[Ressource_26]
	Nom = Sulphur
	NomCompetence = Prospect sulphur

; ************************************************************************************
; *            Paramètres des ressources disponibles sur le terrain                  *
; ************************************************************************************

[Terrain_Ressources]

[TerrainRessource_1]
	Nom = Medicinal herbs

[TerrainRessource_2]
	Nom = Apple tree

[TerrainRessource_3]
	Nom = Wood tree

[TerrainRessource_4]
	Nom = Stone deposit

[TerrainRessource_5]
	Nom = Iron deposit

[TerrainRessource_6]
	Nom = Crystal deposit

[TerrainRessource_7]
	Nom = Gold deposit

[TerrainRessource_8]
	Nom = Sulphur deposit