[Boutons]
AfficherInfoBulle=1
InfoBulleDecalageX=24
InfoBulleDecalageY=20
CouleurInfoBulle=&H0&
CouleurRectangleFond=&HC0FFFF
BordureRectangleFond=2

;Noir : &HFFFFFF
;Blanc : &H80FFFF

CheminBoutonConstruire = "Construire\"
NomBoutonDemolir = "_Demolir"
LargeurBoutonConstruire=28
HauteurBoutonConstruire=28

NomBoutonInfos=Infos
LargeurBoutonInfos=24
HauteurBoutonInfos=24

NomBoutonDeplacement=Deplacement
LargeurBoutonDeplacement=28
HauteurBoutonDeplacement=28

NomBoutonCommerce=Commerce
LargeurBoutonCommerce=24
HauteurBoutonCommerce=24

NomBoutonAction=Action
LargeurBoutonAction=24
HauteurBoutonAction=24

NomBoutonTransfert=Transfert
LargeurBoutonTransfert=24
HauteurBoutonTransfert=24

NomBoutonMenu=Menu
LargeurBoutonMenu=32
HauteurBoutonMenu=32

NomBoutonDefilement=Defilement
LargeurBoutonDefilement=16
HauteurBoutonDefilement=44
LargeurBoutonBarreDefilement=16
HauteurBoutonBarreDefilement=198
LargeurBoutonCarreDefilement=16
HauteurBoutonCarreDefilement=16

NomBoutonObjets=Objets
LargeurBoutonObjets=32
HauteurBoutonObjets=32

NomBoutonCompetences=Competences
LargeurBoutonCompetences=28
HauteurBoutonCompetences=16
