[Cartes]
Chemin = "\Cartes\"

ExtentionImage = ".bmp"
ExtentionTexte = ".txt"

NomImageApercu = Apercu
NomImageTerrain = Terrain
NomImageRessources = Ressources
NomImageChateaux = Chateaux
NomImageCarte = Carte
NomFichierDescription = Description
NomFichierInformations = Informations
CreerFichierInformations =1

NombreTypesTerrains=12
[Terrain_1]
	;Plaine
	;Couleur=#00FF00
	R=0
	V=255
	B=0

[Terrain_2]
	;Herbe
	;Couleur=#339966
	R=49
	V=156
	B=99

[Terrain_3]
	;Terre
	;Couleur=#808000
	R=132
	V=132
	B=0

[Terrain_4]
	;Désert
	;Couleur=#FFFF00
	R=255
	V=255
	B=0

[Terrain_5]
	;Montagne
	;Couleur=#969696
	R=148
	V=148
	B=148

[Terrain_6]
	;Route
	;Couleur=#C0C0C0
	R=198
	V=198
	B=198

[Terrain_7]
	;Muraille1
	;Couleur=#FFCC99
	R=255
	V=206
	B=156
[Terrain_8]
	;Muraille2
	;Couleur=#FFCC00
	R=255
	V=206
	B=0
[Terrain_9]
	;Muraille3
	;Couleur=#FF9900
	R=255
	V=156
	B=0
[Terrain_10]
	;Muraille4
	;Couleur=#FF6600
	R=255
	V=99
	B=0

[Terrain_11]
	;Neige
	;Couleur=#FFFFFF
	R=255
	V=255
	B=255

[Terrain_12]
	;Eau
	;Couleur=#00CEFF
	R=0
	V=206
	B=255

NombreTypesRessources=8
[Ressource_1]
	;Herbes médicinales
	;Couleur=#00CCFF
	R=0
	V=255
	B=0
[Ressource_2]
	;Pommes
	;Couleur=#FF0000
	R=255
	V=0
	B=0
[Ressource_3]
	;Arbres
	;Couleur=#00CCFF
	R=64
	V=192
	B=64
[Ressource_4]
	;Pierre
	;Couleur=#808080
	R=128
	V=128
	B=128
[Ressource_5]
	;Fer
	;Couleur=#C0C0C0
	R=192
	V=192
	B=192
[Ressource_6]
	;Cristaux
	;Couleur=#0000FF
	R=0
	V=0
	B=255
[Ressource_7]
	;Or
	;Couleur=#FFFF00
	R=255
	V=255
	B=0
[Ressource_8]
	;Soufre
	;Couleur=#C0C080
	R=192
	V=192
	B=128
