[Combat]

CoefDegatPerso = 0.5
CoefDegatBatiment = 1
DureeImmobilisation = 0

ChanceCoupCritique = 0.05
CoefDegatCoupCritique = 1
ChanceEchecCritique = 0.05
#Nombre de points d'attaque perdus en cas d'échec critique.
PerteEchecCritique = 20

#Nombre de dégât maximum que l'on inflige quand on tape sur un batiment.
MaxDegatBatiment = 20

#Quantité de ressources prises pendant un combat sur les personnages.
CoefPillageArgentPersoMort = 0.25
CoefPillageRessourcesPersoMort = 0.25
CoefPillageObjetsPersoMort = 0.25
#Chance qu'un objet soit détruit au lieu d'être pillé.
CoefDestructionObjets = 0.5 

#Quantité de ressources prises pendant un combat sur les bâtiments.
CoefPillageArgentMaison = 0.5
CoefPillageRessourcesMaison = 0.5
CoefPillageObjetsMaison = 0.5


[Degats]
#Affichage des points de vie perdus en combat.
AfficherDegats = 1
TailleNormale = 8
TailleCritique = 10
CouleurDegat = &H000000FF&
CouleurGueri = &H00FF0000&
CouleurVente = &H0000FFFF&
DureeMax = 15
DecalageX = 0
DecalageY = -6
DeplacementX = 0
DeplacementY = -1
AfficherInfoBulle=1
