[Fenetres]
NombreFenetres=8

[Fenetre_1]
;Fenetre bâtiment.
Largeur=320
Hauteur=368
Image1=Fenetre-Defaut

[Fenetre_2]
;Fenetre ressources.
Largeur=320
Hauteur=368
Image1=Fenetre-Defaut

[Fenetre_3]
;Fenetre caractéristiques.
Largeur=320
Hauteur=368
Image1=Fenetre-Personnage

[Fenetre_4]
;Fenetre compétences.
Largeur=320
Hauteur=368
Image1=Fenetre-Competences

[Fenetre_5]
;Fenetre inventaire.
Largeur=320
Hauteur=368
NombreImages=4
;Inventaire personnage masculin.
Image1=Fenetre-InventaireH
;Inventaire personnage féminin.
Image2=Fenetre-InventaireF
;Inventaire personnage masculin à la maison.
Image3=Fenetre-InventaireHM
;Inventaire personnage féminin à la maison.
Image4=Fenetre-InventaireFM

[Fenetre_6]
;Fenetre bestiaire.
Largeur=320
Hauteur=368
Image1=Fenetre-Defaut

[Fenetre_7]
;Fenetre carte.
Largeur=320
Hauteur=368
Image1=Fenetre-Carte

[Fenetre_8]
;Fenetre objectifs.
Largeur=320
Hauteur=368
Image1=Fenetre-Defaut