[Jeu]

AffichageRapide=1

FPS=60
FPSMin=5
FPSMax=60

Vitesse=10
VitesseMin=5
VitesseMax=30

AfficherFantomes=0
AfficherFantomesPNJ=0
AfficherProjectiles=1

Mode2Joueurs=0
Mode2JoueursEcranSepares=1

#Invoque ou non les invocations par plusieurs.
Regle1=50

#Temps de rechargement pour les objets.
Regle2=1

#Utilisation du pathfinding. (0 : non, 1 : oui, 2 : avancé)
Regle3=1

#Uniquement le mode confrontation en réseau.
Regle4=1
