[Musiques]
;Paramètres des musiques.
Jouer=1
UtiliserDirectMusic=1

ExtensionMusiques1=.mp3
ExtensionMusiques2=.mid
ExtensionMusiques3=.wav

Chemin=\Musiques\

CheminMenu=Menu\
CheminDebut=Debut\
CheminVille=Ville\
CheminCombat=Combat\
CheminMort=Mort\
CheminVictoire=Victoire\
CheminDefaite=Defaite\
CheminBoss=Boss\
CheminEmpereur=Empereur\

;Nombre de secondes entre chaque musique.
IntervalMusiques = 256
