; ************************************************************************************
; *                            Paramètres des résistances                            *
; ************************************************************************************

[Resistances]
Defaut=1
Minimum=0.2
Maximum=3

[Resistance_1]
	Nom=Physique
	NomComplet=Résistance physique
	Attaque=Attaque physique
	Abreviation=PH

[Resistance_2]
	Nom=Projectiles
	NomComplet=Résistance aux projectiles
	Attaque=Attaque par projectiles
	Abreviation=PR

[Resistance_3]
	Nom=Feu
	NomComplet=Résistance au feu
	Attaque=Attaque de feu
	Abreviation=FE

[Resistance_4]
	Nom=Froid
	NomComplet=Résistance au froid
	Attaque=Attaque de froid
	Abreviation=FR

[Resistance_5]
	Nom=Lumière
	NomComplet=Résistance à la lumière
	Attaque=Attaque lumineuse
	Abreviation=Lu

[Resistance_6]
	Nom=Mort
	NomComplet=Résistance à la mort
	Attaque=Attaque de mort
	Abreviation=MO

[Resistance_7]
	Nom=Eau
	NomComplet=Résistance à l'eau
	Attaque=Attaque d'eau
	Abreviation=EA

[Resistance_8]
	Nom=Electricité
	NomComplet=Résistance à l'électricité
	Attaque=Attaque électrique
	Abreviation=EL

[Statuts]

[Statut_1]
	Nom=Petit
	#Résiste aux flèches. Vulnérable au contact.
	Resistance(1)=1.25
	Resistance(2)=0.75
[Statut_2]
	Nom=Grand
	#Vulnérable aux flèches. Résiste au contact.
	Resistance(1)=0.75
	Resistance(2)=1.25
[Statut_3]
	Nom=Inflammable
	#Vulnérable au feu.
	Resistance(3)=2
[Statut_4]
	Nom=Mouillé
	#Protection contre le feu. Vulnérable au froid et à l'electricité.
	Resistance(3)=0.65
	Resistance(4)=1.25
	Resistance(8)=1.1
[Statut_5]
	Nom=Animal
	#Résiste au froid mais pas au feu.
	Resistance(3)=1.25
	Resistance(4)=0.75
[Statut_6]
	Nom=Mort vivant
	#Résiste aux projectiles, froid. Immunité à la mort.
	Resistance(2)=0.75
	Resistance(4)=0.5
	Resistance(5)=1.5
	Resistance(6)=0
[Statut_7]
	Nom=Esprit
	#Résistant à la lumière mais pas à la mort.
	Resistance(5)=0.5
	Resistance(6)=2
[Statut_8]
	Nom=Esprit d'air
	#Résistant aux flèches.
	Resistance(2)=0.5
[Statut_9]
	Nom=Esprit de feu
	#Immunité au feu.
	Resistance(3)=0
	Resistance(4)=1.5
[Statut_10]
	Nom=Esprit d'eau
	#Immunité à l'eau.
	Resistance(7)=0
[Statut_11]
	Nom=Esprit de terre
	#Résistant physique et à l'eau. Vulnérable au feu.
	Resistance(1)=0.75
	Resistance(2)=0.75
	Resistance(3)=2
	Resistance(7)=0.75
[Statut_12]
	Nom=Esprit de mort
	#Résistant à la mort mais pas à la lumière.
	Resistance(5)=1.5
	Resistance(6)=0.5
[Statut_13]
	Nom=Dragon
	#Résiste au feu
	Resistance(3)=0.5
	Resistance(4)=1.5
[Statut_14]
	Nom=Artificiel
	#Résistance physique et aux flèches. Immunité à la mort.
	Resistance(1)=0.5
	Resistance(2)=0.5
	Resistance(6)=0
[Statut_15]
	Nom=Machine
	#Résistance physique et aux flèches.
	#Vulnérable à l'eau et à l'electricité. Immunité à la mort.
	Resistance(1)=0.75
	Resistance(2)=0.75
	Resistance(7)=2
	Resistance(8)=3
	Resistance(6)=0