; ************************************************************************************
; *                              Paramètres des peuples                              *
; ************************************************************************************

[Peuples]
CheminImageDefaut = Images\Batiments\Chateaux\

[Peuple_1]
	Nom = Humains
	Image = Humains
	NomChateau = Château
	ChateauMaxVie = 2000
	ChateauLargeur = 128
	ChateauHauteur = 128
	ChateauEntreePositionX = 0
	ChateauEntreePositionY = 0
[Peuple_2]
	Nom = Animaux
	Image = Animaux
	NombreMonstres = 6
	MonstreIndice(1) = 7
	MonstreChance(1) = 0.1
	MonstreFichierIA(1) = Eleveur.ia
	MonstreIndice(2) = 13
	MonstreChance(2) = 0.75
	MonstreIndice(3) = 14
	MonstreChance(3) = 0.5
	MonstreIndice(4) = 15
	MonstreChance(4) = 0.5
	MonstreIndice(5) = 16
	MonstreChance(5) = 0.5
	MonstreIndice(6) = 17
	MonstreChance(6) = 0.5
	NomChateau = Ferme abandonnée
	ChateauMaxVie = 2000
	ChateauLargeur = 128
	ChateauHauteur = 128
	ChateauEntreePositionX = 0
	ChateauEntreePositionY = 0
[Peuple_3]
	Nom = Bêtes sauvages
	Image = BetesSauvages
	NombreMonstres = 5
	MonstreIndice(1) = 18
	MonstreChance(1) = 0.75
	MonstreIndice(2) = 19
	MonstreChance(2) = 0.5
	MonstreIndice(3) = 20
	MonstreChance(3) = 0.5
	MonstreIndice(4) = 21
	MonstreChance(4) = 0.5
	MonstreIndice(5) = 22
	MonstreChance(5) = 0.5
	NomChateau = Jungle sauvage
	ChateauMaxVie = 2000
	ChateauLargeur = 128
	ChateauHauteur = 128
	ChateauEntreePositionX = 0
	ChateauEntreePositionY = 0
[Peuple_4]
	Nom = Morts-vivants
	Image = MortsVivants
	NombreMonstres = 6
	MonstreIndice(1) = 11
	MonstreChance(1) = 0.1
	MonstreFichierIA(1) = Necromancien offensif.ia
	MonstreIndice(2) = 23
	MonstreChance(2) = 0.75
	MonstreIndice(3) = 24
	MonstreChance(3) = 0.5
	MonstreIndice(4) = 25
	MonstreChance(4) = 0.5
	MonstreIndice(5) = 26
	MonstreChance(5) = 0.5
	MonstreIndice(6) = 27
	MonstreChance(6) = 0.5
	NomChateau = Cimetière maudit
	ChateauMaxVie = 2000
	ChateauLargeur = 128
	ChateauHauteur = 128
	ChateauEntreePositionX = 0
	ChateauEntreePositionY = 0
[Peuple_5]
	Nom = Sorciers
	Image = Sorciers
	NombreMonstres = 5
	MonstreIndice(1) = 28
	MonstreChance(1) = 0.75
	MonstreIndice(2) = 29
	MonstreChance(2) = 0.5
	MonstreIndice(3) = 30
	MonstreChance(3) = 0.5
	MonstreIndice(4) = 31
	MonstreChance(4) = 0.5
	MonstreIndice(5) = 32
	MonstreChance(5) = 0.5
	NomChateau = Tour de mage
	ChateauMaxVie = 2000
	ChateauLargeur = 128
	ChateauHauteur = 128
	ChateauEntreePositionX = 0
	ChateauEntreePositionY = 0
[Peuple_6]
	Nom = Hommes-bêtes
	Image = HommesBetes
	NombreMonstres = 6
	MonstreIndice(1) = 10
	MonstreChance(1) = 0.1
	MonstreIndice(2) = 33
	MonstreChance(2) = 0.75
	MonstreIndice(3) = 34
	MonstreChance(3) = 0.5
	MonstreIndice(4) = 35
	MonstreChance(4) = 0.5
	MonstreIndice(5) = 36
	MonstreChance(5) = 0.5
	MonstreIndice(6) = 37
	MonstreChance(6) = 0.5
	NomChateau = Repère des hommes-bêtes
	ChateauMaxVie = 2000
	ChateauLargeur = 128
	ChateauHauteur = 128
	ChateauEntreePositionX = 0
	ChateauEntreePositionY = 0
[Peuple_7]
	Nom = Technologistes
	Image = Technologistes
	NombreMonstres = 5
	MonstreIndice(1) = 38
	MonstreChance(1) = 0.75
	MonstreIndice(2) = 39
	MonstreChance(2) = 0.5
	MonstreIndice(3) = 40
	MonstreChance(3) = 0.5
	MonstreIndice(4) = 41
	MonstreChance(4) = 0.5
	MonstreIndice(5) = 42
	MonstreChance(5) = 0.5
	NomChateau = Centre de recherche
	ChateauMaxVie = 2000
	ChateauLargeur = 128
	ChateauHauteur = 128
	ChateauEntreePositionX = 0
	ChateauEntreePositionY = 0
[Peuple_8]
	Nom = Sylvestres
	Image = Sylvestres
	NombreMonstres = 6
	MonstreIndice(1) = 77
	MonstreChance(1) = 0.3
	MonstreIndice(2) = 3
	MonstreChance(2) = 0.3
	MonstreFichierIA(2) = Archer.ia
	MonstreIndice(3) = 81
	MonstreChance(3) = 0.3
	MonstreIndice(4) = 8
	MonstreChance(4) = 0.5
	MonstreFichierIA(4) = Clerc.ia
	MonstreIndice(5) = 78
	MonstreChance(5) = 0.5
	MonstreIndice(6) = 79
	MonstreChance(6) = 0.5
	NomChateau = Arbre ancestral
	ChateauMaxVie = 2000
	ChateauLargeur = 128
	ChateauHauteur = 141
	ChateauEntreePositionX = 1
	ChateauEntreePositionY = 49
[Peuple_9]
	Nom = Pillards
	Image = Pillards
	NombreMonstres = 6
	MonstreIndice(1) = 1
	MonstreChance(1) = 0.1
	MonstreFichierIA(1) = Mercenaire.ia
	MonstreIndice(2) = 43
	MonstreChance(2) = 0.75
	MonstreIndice(3) = 44
	MonstreChance(3) = 0.5
	MonstreIndice(4) = 45
	MonstreChance(4) = 0.5
	MonstreIndice(5) = 46
	MonstreChance(5) = 0.5
	MonstreIndice(6) = 47
	MonstreChance(6) = 0.5
	NomChateau = Camp de pillards
	ChateauMaxVie = 2000
	ChateauLargeur = 128
	ChateauHauteur = 128
	ChateauEntreePositionX = 0
	ChateauEntreePositionY = 0
[Peuple_10]
	Nom = Impériaux
	Image = Imperiaux
	NombreMonstres = 5
	MonstreIndice(1) = 48
	MonstreChance(1) = 0.75
	MonstreIndice(2) = 49
	MonstreChance(2) = 0.5
	MonstreIndice(3) = 50
	MonstreChance(3) = 0.5
	MonstreIndice(4) = 51
	MonstreChance(4) = 0.5
	MonstreIndice(5) = 52
	MonstreChance(5) = 0.5
	NomChateau = Forteresse impériale
	ChateauMaxVie = 2000
	ChateauLargeur = 128
	ChateauHauteur = 128
	ChateauEntreePositionX = 0
	ChateauEntreePositionY = 0
[Peuple_11]
	Nom = Démons
	Image = Demons
	NombreMonstres = 5
	MonstreIndice(1) = 53
	MonstreChance(1) = 0.75
	MonstreIndice(2) = 54
	MonstreChance(2) = 0.5
	MonstreIndice(3) = 55
	MonstreChance(3) = 0.5
	MonstreIndice(4) = 56
	MonstreChance(4) = 0.5
	MonstreIndice(5) = 57
	MonstreChance(5) = 0.5
	NomChateau = Donjon démoniaque
	ChateauMaxVie = 2000
	ChateauLargeur = 128
	ChateauHauteur = 128
	ChateauEntreePositionX = 0
	ChateauEntreePositionY = 0
[Peuple_12]
	Nom = Elémentaux
	Image = Elementaux
	NombreMonstres = 9
	MonstreIndice(1) = 58
	MonstreChance(1) = 0.75
	MonstreIndice(2) = 59
	MonstreChance(2) = 0.5
	MonstreIndice(3) = 60
	MonstreChance(3) = 0.5
	MonstreIndice(4) = 61
	MonstreChance(4) = 0.5
	MonstreIndice(5) = 62
	MonstreChance(5) = 0.5
	MonstreIndice(6) = 93
	MonstreChance(6) = 0.25
	MonstreIndice(7) = 94
	MonstreChance(7) = 0.25
	MonstreIndice(8) = 95
	MonstreChance(8) = 0.25
	MonstreIndice(9) = 96
	MonstreChance(9) = 0.25
	NomChateau = Cercle élémentaire
	ChateauMaxVie = 2000
	ChateauLargeur = 128
	ChateauHauteur = 128
	ChateauEntreePositionX = 0
	ChateauEntreePositionY = 0
[Peuple_13]
	Nom = Dragons
	Image = Dragons
	NombreMonstres = 6
	MonstreIndice(1) = 9
	MonstreChance(1) = 0.1
	MonstreIndice(2) = 63
	MonstreChance(2) = 0.75
	MonstreIndice(3) = 64
	MonstreChance(3) = 0.5
	MonstreIndice(4) = 65
	MonstreChance(4) = 0.5
	MonstreIndice(5) = 66
	MonstreChance(5) = 0.5
	MonstreIndice(6) = 67
	MonstreChance(6) = 0.5
	NomChateau = Tanière des dragons
	ChateauMaxVie = 2000
	ChateauLargeur = 128
	ChateauHauteur = 128
	ChateauEntreePositionX = 0
	ChateauEntreePositionY = 0