; ************************************************************************************
; *                             Paramètres des décors                                *
; ************************************************************************************

[Decors]

[Decor_1]
Nom=Pont
Image=Pont
Largeur=71
Hauteur=88

[Decor_2]
Nom=Drapeau
Image=Drapeau
Largeur=31
Hauteur=81

[Decor_3]
Nom=Fontaine
Image=Fontaine
Largeur=89
Hauteur=86
NombreEtapeAnimation=4

[Decor_4]
Nom=Tombe
Image=Pierre tombale3
Largeur=23
Hauteur=17
Duree=60

[Decor_5]
Nom=Tombe2
Image=Croix
Largeur=14
Hauteur=22
Duree=60