[Personnages]
FichiersSelection=0
CompetencesSelection=0
CompetencesAfficherToutes=0
CompetencesTri=2
CompetencesAffichage=0
NombrePersonnages=3
DernierPersonnage=2
PersonnageJoueur1=0
PersonnageJoueur2=1
Personnage0=0
Personnage1=0
Personnage2=1
Personnage3=0
Personnage4=0
Personnage5=0
Personnage6=0
Personnage7=0
Personnage8=1
Personnage9=0
Personnage10=0
Personnage11=0
Personnage12=0
Personnage13=0
Personnage14=0
Personnage15=0
Personnage16=0
Personnage17=0
Personnage18=0
Personnage19=0
Personnage20=1
Personnage21=1
Personnage22=1
Personnage23=1
Personnage24=1
Personnage25=1
Personnage26=1
Personnage27=1
Personnage28=1
Personnage29=1
Personnage30=1
Personnage31=1
Personnage32=1
Personnage33=1
Personnage34=1
Personnage35=1
Personnage36=1
Personnage37=1
Personnage38=1
Personnage39=1
Personnage40=1
Personnage41=1
Personnage42=1
Personnage43=1
Personnage44=1
Personnage45=1
Personnage46=1
Personnage47=1
Personnage48=1
Personnage49=1
Personnage50=1
Personnage51=1
Personnage52=1
Personnage53=1
Personnage54=1
Personnage55=1
Personnage56=1
Personnage57=1
Personnage58=1
Personnage59=1
Personnage60=1
Personnage61=0
Personnage62=0
Personnage63=0
Personnage64=0
Personnage65=0
Personnage66=0
Personnage67=0
Personnage68=0
Personnage69=0
Personnage70=0
Personnage71=0
Personnage72=0
Personnage73=0
Personnage74=0
Personnage75=0
Personnage76=0
Personnage77=0
Personnage78=0
Personnage79=0
Personnage80=0
Personnage81=0
Personnage82=0
Personnage83=0
Personnage84=0
Personnage85=0
Personnage86=0
Personnage87=0
Personnage88=0
Personnage89=0
Personnage90=0
Personnage91=0
Personnage92=0
Personnage93=0
Personnage94=0
Personnage95=0
Personnage96=0
Personnage97=0
Personnage98=0
Personnage99=0
Personnage100=0
Personnage101=0
Personnage102=0
Personnage103=0
Personnage104=0
Personnage105=0

[Campagnes]
DerniereCampagne=1
DernierScenario=0

[Monde]
DernierMonde=0
DernierScenario=0
TypePartie=1
TypeCarte=2
DerniereCarte=5
DernierePartie=1

NombreTailles=8
TailleChoisie=3

#Taille1Nom=Tiny (2 fiefs)
Taille1Dimensions=128*128
Taille1Ressources=50
Taille1Fiefs=2

#Taille2Nom=Small (3 fiefs)
Taille2Dimensions=192*192
Taille2Ressources=100
Taille2Fiefs=3

#Taille3Nom=Medium (4 fiefs)
Taille3Dimensions=256*256
Taille3Ressources=200
Taille3Fiefs=4

#Taille4Nom=Great (6 fiefs)
Taille4Dimensions=384*384
Taille4Ressources=400
Taille4Fiefs=6

#Taille5Nom=Large (8 fiefs)
Taille5Dimensions=512*512
Taille5Ressources=800
Taille5Fiefs=8

#Taille6Nom=Huge (10 fiefs)
Taille6Dimensions=640*640
Taille6Ressources=1200
Taille6Fiefs=10

#Taille7Nom=Big (12 fiefs)
Taille7Dimensions=768*768
Taille7Ressources=2000
Taille7Fiefs=12

#Taille8Nom=Gigantic (16 fiefs)
Taille8Dimensions=1024*1024
Taille8Ressources=3200
Taille8Fiefs=16

TerrainChoisi=2

NombreRessources=3
RessourceChoisie=2
#Ressources1Nom=Low
Ressources1Multiplicateur=0.5
#Ressources2Nom=Standard
Ressources2Multiplicateur=1
#Ressources3Nom=High
Ressources3Multiplicateur=2

EpoqueChoisie=1
RessourcesDepartsChoisie=1
VitesseEpoqueChoisie =3

MinLargeur=128
MinHauteur=128
MinQuantitéRessources=20

ValLargeur=256
ValHauteur=256
ValQuantitéRessources=200

MaxLargeur=1024
MaxHauteur=1024
MaxQuantitéRessources=6400

DifficulteChoisie=1
NombreDifficultes=12

#Difficulte1Nom=Normal
Difficulte1BonusXP=0
Difficulte1CoefVieChateaux=1
#Difficulte2Nom=Trained (Lvl 10)
Difficulte2BonusXP=1100
Difficulte2CoefVieChateaux=1.5
#Difficulte3Nom=Champion (Lvl 20)
Difficulte3BonusXP=4200
Difficulte3CoefVieChateaux=2
#Difficulte4Nom=Expert (Lvl 30)
Difficulte4BonusXP=9300
Difficulte4CoefVieChateaux=2.5
#Difficulte5Nom=Master (Lvl 40)
Difficulte5BonusXP=16400
Difficulte5CoefVieChateaux=3
#Difficulte6Nom=Hero (Lvl 50)
Difficulte6BonusXP=25500
Difficulte6CoefVieChateaux=3.5
#Difficulte7Nom=Elite (Lvl 60)
Difficulte7BonusXP=36600
Difficulte7CoefVieChateaux=4
#Difficulte8Nom=Messiah (Lvl 70)
Difficulte8BonusXP=49700
Difficulte8CoefVieChateaux=4.5
#Difficulte9Nom=Legend (Lvl 80)
Difficulte9BonusXP=64800
Difficulte9CoefVieChateaux=5
#Difficulte10Nom=Half god (Lvl 90)
Difficulte10BonusXP=81900
Difficulte10CoefVieChateaux=5.5
#Difficulte11Nom=Divinity (Lvl 100)
Difficulte11BonusXP=101000
Difficulte11CoefVieChateaux=6
#Difficulte12Nom=Crazy (Lvl 1000)
Difficulte12BonusXP=10010000
Difficulte12CoefVieChateaux=51

[Resurrections_Nombre]
ResurrectionChoisie=7
NombreResurrections=7
#Resurrection1Nom=Forbidden
Resurrection1Valeur=0
#Resurrection2Nom=1 time
Resurrection2Valeur=1
#Resurrection3Nom=3 times
Resurrection3Valeur=3
#Resurrection4Nom=10 times
Resurrection4Valeur=10
#Resurrection5Nom=25 times
Resurrection5Valeur=25
#Resurrection6Nom=100 times
Resurrection6Valeur=100
#Resurrection7Nom=Unlimited
Resurrection7Valeur=-1

[Resurrections_Vitesse]
ResurrectionChoisie=3
NombreResurrections=6
#Resurrection1Nom=Very slow
Resurrection1Valeur=0.25
#Resurrection2Nom=slow
Resurrection2Valeur=0.5
#Resurrection3Nom=Average
Resurrection3Valeur=1
#Resurrection4Nom=Fast
Resurrection4Valeur=2
#Resurrection5Nom=Very fast
Resurrection5Valeur=4
#Resurrection6Nom=Instantaneous
Resurrection6Valeur=100

[Fiefs]
MinFiefs=2
ValFiefs=4
MaxFiefs=16
EquilibreFiefs=1

MinVillageoisFief=1
MaxVillageoisFief=250

ValVillageoisFief1=50
ValVillageoisFief2=50
ValVillageoisFief3=50
ValVillageoisFief4=50
ValVillageoisFief5=50
ValVillageoisFief6=50
ValVillageoisFief7=50
ValVillageoisFief8=50
ValVillageoisFief9=50
ValVillageoisFief10=50
ValVillageoisFief11=50
ValVillageoisFief12=50
ValVillageoisFief13=50
ValVillageoisFief14=50
ValVillageoisFief15=50
ValVillageoisFief16=50
ValVillageoisFief17=50
ValVillageoisFief18=50

PeupleFief1=1
PeupleFief2=14
PeupleFief3=14
PeupleFief4=14
PeupleFief5=14
PeupleFief6=14
PeupleFief7=14
PeupleFief8=14
PeupleFief9=14
PeupleFief10=14
PeupleFief11=14
PeupleFief12=14
PeupleFief13=14
PeupleFief14=14
PeupleFief15=14
PeupleFief16=14
PeupleFief17=13
PeupleFief18=13

EquipeFief1=1
EquipeFief2=2
EquipeFief3=3
EquipeFief4=4
EquipeFief5=5
EquipeFief6=6
EquipeFief7=7
EquipeFief8=8
EquipeFief9=9
EquipeFief10=10
EquipeFief11=11
EquipeFief12=12
EquipeFief13=13
EquipeFief14=14
EquipeFief15=15
EquipeFief16=16
EquipeFief17=17
EquipeFief18=18

[Bataille]
[Armée_1]
MinSoldats=1
ValSoldats=100
MaxSoldats=300
Peuple=1
Equipement=0
Objet0=0
Objet1=0
Objet2=0
Objet3=0
Objet4=0
Objet5=0
Objet6=0
Objet7=0
Objet8=0
Objet9=0
Objet10=0
Objet11=0
Objet12=0
Objet13=0
Objet14=0
Objet15=0
Objet16=0
Objet17=0
Objet18=0
Objet19=0
Objet20=0
Objet21=0
Objet22=0
Objet23=0
Objet24=0
Objet25=0
Objet26=0
Objet27=0
Objet28=0
Objet29=0
Objet30=0
Objet31=0
Objet32=0
Objet33=0
Objet34=0
Objet35=0
Objet36=0
Objet37=0
Objet38=0
Objet39=0
Objet40=0
Objet41=0
Objet42=0
Objet43=0
Objet44=0
Objet45=0
Objet46=0
Objet47=0
Objet48=0
Objet49=0
Objet50=0
Objet51=0
Objet52=0
Objet53=0
Objet54=0
Objet55=0
Objet56=0
Objet57=0
Objet58=0
Objet59=0
Objet60=0
Objet61=0
Objet62=0
Objet63=0
Objet64=0
Objet65=0
Objet66=0
Objet67=0
Objet68=0
Objet69=0
Objet70=0
Objet71=0
Objet72=0
Objet73=0
Objet74=0
Objet75=0
Objet76=0
Objet77=0
Objet78=1
Objet79=0
Objet80=0
Objet81=0
Objet82=0
Objet83=0
Objet84=0
Objet85=0
Objet86=0
Objet87=0
Objet88=0
Objet89=0
Objet90=0
Objet91=0
Objet92=0
Objet93=0
Objet94=0
Objet95=0
Objet96=0
Objet97=0
Objet98=0
Objet99=0
Objet100=0
Objet101=0
Objet102=0
Objet103=0
Objet104=0
Objet105=0
Objet106=0
Objet107=0
Objet108=0
Objet109=0
Objet110=0
Objet111=0
Objet112=0
Objet113=0
Objet114=0
Objet115=0
Objet116=0
Objet117=0
Objet118=0
Objet119=0
Objet120=0
Objet121=0
Objet122=0
Objet123=0
Objet124=0
Objet125=0
Objet126=0
Objet127=0
Objet128=0
Objet129=0
Objet130=0
Objet131=0
Objet132=0
Objet133=0
Objet134=0
Objet135=0
Objet136=0
Objet137=0
Objet138=0
Objet139=0
Objet140=0
Objet141=0
Objet142=0
Objet143=0
Objet144=0
Objet145=0
Objet146=0
Objet147=0
Objet148=0
Objet149=0
Objet150=0
Objet151=0
Objet152=0
Objet153=0
Objet154=0
Objet155=0
Objet156=0
Objet157=0
Objet158=0
Objet159=0
Objet160=0
Objet161=0
Objet162=0
Objet163=0
Objet164=0
Objet165=0
[Armée_2]
MinSoldats=1
ValSoldats=100
MaxSoldats=300
Peuple=14
Equipement=0
Objet0=0
Objet1=0
Objet2=0
Objet3=0
Objet4=0
Objet5=0
Objet6=0
Objet7=0
Objet8=0
Objet9=0
Objet10=0
Objet11=0
Objet12=0
Objet13=0
Objet14=0
Objet15=0
Objet16=0
Objet17=0
Objet18=0
Objet19=0
Objet20=0
Objet21=0
Objet22=0
Objet23=0
Objet24=0
Objet25=0
Objet26=0
Objet27=0
Objet28=0
Objet29=0
Objet30=0
Objet31=0
Objet32=0
Objet33=0
Objet34=0
Objet35=0
Objet36=0
Objet37=0
Objet38=0
Objet39=0
Objet40=0
Objet41=0
Objet42=0
Objet43=0
Objet44=0
Objet45=0
Objet46=0
Objet47=0
Objet48=0
Objet49=0
Objet50=0
Objet51=0
Objet52=0
Objet53=0
Objet54=0
Objet55=0
Objet56=0
Objet57=0
Objet58=0
Objet59=0
Objet60=0
Objet61=0
Objet62=0
Objet63=0
Objet64=0
Objet65=0
Objet66=0
Objet67=0
Objet68=0
Objet69=0
Objet70=0
Objet71=0
Objet72=0
Objet73=0
Objet74=0
Objet75=0
Objet76=0
Objet77=0
Objet78=0
Objet79=0
Objet80=0
Objet81=0
Objet82=0
Objet83=0
Objet84=0
Objet85=0
Objet86=0
Objet87=0
Objet88=0
Objet89=0
Objet90=0
Objet91=0
Objet92=0
Objet93=0
Objet94=0
Objet95=0
Objet96=0
Objet97=0
Objet98=0
Objet99=0
Objet100=0
Objet101=0
Objet102=0
Objet103=0
Objet104=0
Objet105=0
Objet106=0
Objet107=0
Objet108=0
Objet109=0
Objet110=0
Objet111=0
Objet112=0
Objet113=0
Objet114=0
Objet115=0
Objet116=0
Objet117=0
Objet118=0
Objet119=0
Objet120=0
Objet121=0
Objet122=0
Objet123=0
Objet124=0
Objet125=0
Objet126=0
Objet127=0
Objet128=0
Objet129=0
Objet130=0
Objet131=0
Objet132=0
Objet133=0
Objet134=0
Objet135=0
Objet136=0
Objet137=0
Objet138=0
Objet139=0
Objet140=0
Objet141=0
Objet142=0
Objet143=0
Objet144=0
Objet145=0
Objet146=0
Objet147=0
Objet148=0
Objet149=0
Objet150=0
Objet151=0
Objet152=0
Objet153=0
Objet154=0
Objet155=0
Objet156=0
Objet157=0
