[Temps]

Chemin = "Temps\"

Afficher =0
Largeur = 512
Hauteur = 512

NombreTemps = 11
JourneeDebut = 9
JourneeVitesse = 0.08

[Temp_1]
#La nuit.
Debut = 0
Afficher = 1
Image = Nuit

#Le matin.
[Temp_2]
Debut = 3
Afficher = 1
Image = Soir4

[Temp_3]
Debut = 4
Afficher = 1
Image = Soir3

[Temp_4]
Debut = 5
Afficher = 1
Image = Soir2

[Temp_5]
Debut = 6
Afficher = 1
Image = Soir1

#Le jour.
[Temp_6]
Debut = 7
Afficher = 0
Image = 

#Le soir.
[Temp_7]
Debut = 17
Afficher = 1
Image = Soir1

[Temp_8]
Debut = 18
Afficher = 1
Image = Soir2

[Temp_9]
Debut = 19
Afficher = 1
Image = Soir3

[Temp_10]
Debut = 20
Afficher = 1
Image = Soir4

#La nuit.
[Temp_11]
Debut = 21
Afficher = 1
Image = Nuit
