[Touches]

;Correspondance des touches du clavier.

ToucheQuitter = 1
;Echap

ToucheZoomNormal = 55
;*
ToucheZoomPlus = 78
;+
ToucheZoomMoins = 74
;-

ToucheDialogue = 86
;<

ToucheFenetreBatiment = 48
;B
ToucheFenetrePersonnage = 25
;P
ToucheFenetreRessources = 19
;R
ToucheFenetreCompetences = 20
;T
ToucheFenetreInventaire = 23
;I
ToucheFenetreBestiaire = 22
;U
ToucheFenetreObjectifs = 87
;F11
ToucheFenetreCarte = 15
;Tab
ToucheFenetresFermer = 57
;Espace

ToucheAction = 28
;Entrée
ToucheRetourChateau = 34
;G
ToucheRetourMaison = 39
;M
ToucheTrouverRessource1 = 59
;F1
ToucheTrouverRessource2 = 60
;F2
ToucheTrouverRessource3 = 61
;F3
ToucheTrouverRessource4 = 62
;F4
ToucheTrouverRessource5 = 63
;F5
ToucheTrouverRessource6 = 64
;F6
ToucheTrouverRessource7 = 65
;F7
ToucheTrouverRessource8 = 66
;F8
ToucheTrouverAttaquerPerso = 44
;W
ToucheTrouverAttaquerMaison = 45
;X
ToucheTrouverAttaquerChateau = 46
;C
ToucheTrouverTresor = 47
;V
ToucheModeAuto = 16
;A
ToucheAide = 35
;H
ToucheArret = 31
;S
;ToucheChargez = 24
;O
ToucheDefinirAttitude1 = 32
;D
ToucheDefinirAttitude2 = 17
;Z
ToucheDefinirAttitude3 = 38
;L
ToucheDefinirAttitude4 = 30
;Q
ToucheDefinirAttitude5 = 37
;K
ToucheDefinirFormation = 33
;F

ToucheArgentDeposer = 201
;Page Préc
ToucheArgentRecuperer = 209
;Page Suiv

ToucheDemolirMaison = 211
;Suppr
ToucheAfficherConseil = 67
;F9
ToucheMenu = 68
;F10
ToucheMusique = -1
;Ctrl+M : 39
ToucheCaptureEcran = -1
;F11    : 87
ToucheSauvegarderMonde = 88
;F12
ToucheInterfacePleinEcran = 14
;Backspace

ToucheChangerPersonnage = 41
;²
ToucheDirectionHaut = -1
;Flèche haut : 200
ToucheDirectionBas = -1
;Flèche bas : 208 
ToucheDirectionGauche = -1
;Flèche gauche : 203
ToucheDirectionDroite = -1
;Flèche droite : 205


ToucheObjets = 2
NombreTouchesObjets = 9

ToucheSoldatsToutes = 16
;Ctrl+A
ToucheSoldatsMemeType = 17
;Ctrl+Z
ToucheSoldatsEnArme = 44
;Ctrl+W 
ToucheSoldatsEcran = 18
;Ctrl+E
ToucheSoldatsReposes = 19
;Ctrl+R
ToucheSoldatsEnArret = 31
;Ctrl+S
ToucheSoldatsRapides = 30
;Ctrl+Q
ToucheSoldatsNonAffectees = 45
;Ctrl+X
ToucheSoldatsTerrestres = 46
;Ctrl+C
ToucheSoldatsVolants = 47
;Ctrl+V
ToucheSoldatsDefensifs = 32
;Ctrl+D
ToucheSoldatsOffensifs = 33
;Ctrl+F
ToucheSoldatsInverser = 23
;Ctrl+I
ToucheSoldatsSupprimer = 211
;Ctrl+Suppr